session/src/main/java/uk/gov/di/ipv/cri/address/api/handler/SessionHandler.java
session/src/test/java/uk/gov/di/ipv/cri/address/api/handler/SessionHandlerTest.java

There are some conflicts on SessionHandler on a  [PR that existed before](https://github.com/alphagov/di-ipv-cri-address-api/pull/109) we moved some lambdas  to this common lambdas repo.
I'm moving the files causing that conflict to this common lambdas repo.

KBV-342 Record audit events in Session Handler

---

session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java

Added changes to integrate audit events CRI's. This works as a temporary fix that needs to be revisited later down the line. 
It may need some discussion around how we plan to use the `audience` parameter in the JWK
- [KBV-432](https://govukverify.atlassian.net/browse/KBV-432)

Integrate audit event feature for KBV CRI

---

session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java

- Utilise the new simplified events
The SQS Event System was very tailored to each service, despite being in the common libraries - this meant keeping a list of enums for all CRIs within the common library - this would not be maintainable in the long run.
Considering these all consisted of the CRI name as a prefix, we decided to move this prefix to an environment variable and prepend it to the event
- [KBV-517](https://govukverify.atlassian.net/browse/KBV-517)

[KBV-517] Amend Audit Service and Calls

---

.github/workflows/post-merge-deploy-to-poc.yml
infrastructure/lambda/template.yaml

- List more GHA working directory contents
- Change session lambda function codeUri
- Attempt to diagnose / fix failing deployment

OJ-892 - attempt to correct codeUri for session lambda function

---

accesstoken/build.gradle
authorization/build.gradle
authorization/src/test/java/uk/gov/di/ipv/cri/common/api/handler/AuthorizationHandlerTest.java
session/build.gradle

- Removed dependency on common-lib project / git submodule
- Added reference to new cri-common-lib jar
- To enable the common-lib git submodule to be retired
- [OJ-933](https://govukverify.atlassian.net/browse/OJ-933)
- The Address / KBV / Fraud CRI will need to be updated in order to use this latest version of the common-lambdas git submodule

Oj 933 add common lib jar dependency

---

.github/workflows/post-merge-matrix-deploy.yml
README.md

Updated matrix workflow to include java build and signing steps
Missing from previous iteration which failed the deployment
- [OJ-934](https://govukverify.atlassian.net/browse/OJ-934)
None

OJ-934 update matrix common CRI deployment

---

.github/workflows/post-merge-matrix-deploy.yml

The matrix workflow has been updated to correct a syntax error 
Without the fix the deployment workflow fails to run
- [OJ-934](https://govukverify.atlassian.net/browse/OJ-934)
None

OJ-934 fix workflow syntax

---

build.gradle
settings.gradle

- Specify project dir for lambda functions 
- This was missed in the previous PR

OJ-892 - fix standalone build

---

infrastructure/lambda/template.yaml

Add log groups referenced but not defined in the cloud formation template
The subscription filters refer to the missing log groups in Build+ which causes the deployment to fail.
- [OJ-934](https://govukverify.atlassian.net/browse/OJ-934)
None

OJ-934 Add missing log groups

---

build.gradle
session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java

Get "x-forwarded-for"  header value from /session api to get the ip address and send it to Persistence layer.
Reading the header value "x-forwarded-for" for session API and storing.
To reuse Client IP address of client to send to TXMA.
- [OJ-924](https://govukverify.atlassian.net/browse/OJ-924)

OJ-924: Save client ip address provided to /session API call

---

infrastructure/lambda/template.yaml

- The CRI-specific mappings have now been updated to include the address & fraud CRIs
- To ensure the common-lambdas stack works for all current live CRIs
- [OJ-968](https://govukverify.atlassian.net/browse/OJ-968)

Update the SAM template mappings for the address & fraud CRIs

---

authorization/src/main/java/uk/gov/di/ipv/cri/common/api/handler/AuthorizationHandler.java
build.gradle

Added error handling for access denied oauth error (for routing back to IpvCore) in authorization lambda
So that correct access denied error can be returned to Ipv core in the event of a user escaping mid journey (e.c in Driving licence Cri)

LIME-147 - Adding accessDenied error handling to authorization lambda

---

integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/runners/RunCucumberTest.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java

We have created a happy case scenario to test session endpoint
This test will act as a QA gateway.
https://govukverify.atlassian.net/browse/OJ-997
STACK_NAME=di-ipv-cri-xxx 
API_GATEWAY_ID_PRIVATE=xxx 
IPV_CORE_STUB_BASIC_AUTH_USER=xxx 
IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxx 
IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digital" 
`STACK_NAME=di-ipv-cri-xxx  API_GATEWAY_ID_PRIVATE=xxx  IPV_CORE_STUB_BASIC_AUTH_USER=xxx IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxx IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digital"  gradle integration-tests:cucumber`

OJ-997 - Added new integration test for session endpoint

---

infrastructure/lambda/template.yaml

- Added driving-permit CRI specific configuration to the existing mappings in `template.yaml`
The values were obtained from: 
https://github.com/alphagov/di-ipv-cri-dl-api/blob/main/infrastructure/lambda/template.yaml
- To enable the driving-permit CRI to transition to the common CRI framework
- [OJ-999](https://govukverify.atlassian.net/browse/OJ-999)

OJ-999 - Add driving-permit CRI configuration

---

authorization/src/main/java/uk/gov/di/ipv/cri/common/api/handler/AuthorizationHandler.java
infrastructure/lambda/template.yaml
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
integration-tests/src/test/resources/features/AuthorizationAPI.feature
integration-tests/src/test/resources/features/SessionAPI.feature

Add cucumber integration test to the `di-ipv-cri-common-lambdas` for `authorization` end point
- It was found during development that it is imperative to call the `AddressHandler` first before we invoke the Authorization handler as that in turn creates the `authorization code`. This code is `mandatory` when sending back the Authorization response. Without this code, the integration test for Authorization Handler will never pass.
- It has also been discussed if `authorization code` should be responsibility of the `cris`. This opened a few implications that all the handlers will need to be amended/changed and tested.
- A simpler fix was to call the code to create the `authorization code` within the Authorization Handler. This way there was no change on any of the `cris`. The `authorization …

OJ-1001: Add Authorization integration test

---

.github/workflows/pre-merge-integration-test.yml
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
integration-tests/src/test/resources/features/AccessTokenAPI.feature
integration-tests/src/test/resources/features/AuthorizationAPI.feature

Add cucumber integration test to the `di-ipv-cri-common-lambdas` for `access token` end point
- It is imperative to call the `session` and `authorization` end points before invoking the `access token` end point
- Added new `feature` file for Access Token end point
- New steps added to the `APISteps` file
- [OJ-1014](https://govukverify.atlassian.net/browse/OJ-1014)
To run the tests:
`STACK_NAME=di-ipv-cri-address-xxxx API_GATEWAY_ID_PRIVATE=xxxx IPV_CORE_STUB_BASIC_AUTH_USER=xxxx IPV_CORE_STUB_BASIC_AUTH_PASSWORD=xxxx IPV_CORE_STUB_URL="https://di-ipv-core-stub.london.cloudapps.digital" APIGW_API_KEY=xxxx gradle integration-tests:cucumber`

OJ-1014: Add Access Token integration test

---

accesstoken/build.gradle
accesstoken/src/main/java/uk/gov/di/ipv/cri/common/api/handler/AccessTokenHandler.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/AccessTokenHandlerTest.java
authorization/src/main/java/uk/gov/di/ipv/cri/common/api/handler/AuthorizationHandler.java
authorization/src/test/java/uk/gov/di/ipv/cri/common/api/handler/AuthorizationHandlerTest.java
build.gradle
session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java

- Log `govuk_signin_journey_id`
- To align with the logging already present in `address-api` and help with debugging / understanding live user journeys
- [OJ-993](https://govukverify.atlassian.net/browse/OJ-993)

OJ-993 - log govuk_signin_journey_id

---

.github/workflows/post-merge-matrix-deploy.yml
.secrets.baseline

The CIC CRI is added to the list of CRIs in the GitHub post-merge-matrix-deploy workflow.
New secrets are referenced, which will need to be added to this repo.
To allow for deployment of the Common infrastructure pipeline in the F2F AWS accounts.
- [F2F-136](https://govukverify.atlassian.net/browse/F2F-136)

F2F-136: Adding the CIC CRI to the GitHub workflows

---

.github/workflows/pre-commit.yml
.github/workflows/pre-merge-checks.yml
.github/workflows/pre-merge-integration-test.yml

Custom workflow step changed from using set-output to be out of scope of GitHub deprecations
The workflow will fail soon if this is not changed
- [OJ-1146](https://govukverify.atlassian.net/browse/OJ-1146)
[OJ-1146]: https://govukverify.atlassian.net/browse/OJ-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1146 update custom output

---

infrastructure/lambda/template.yaml

Renamed driving permit to dl in lambda names
Driving permit was renamed to DL after this was created as the name was too long for aws
- [LIME-421](https://govukverify.atlassian.net/browse/LIME-421)
[LIME-421]: https://govukverify.atlassian.net/browse/LIME-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-421: Renamed driving permit to DL

---

.github/workflows/pre-merge-integration-test.yml
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java

Api key is only used for non dev enviroments and not required for dev as a result it is also not required during pre-merge tes
Remove the specification of public api key as an environment variable
Corresponding environment variable removed  
Discovered during QA exploration of how to run the common lambda api from the commandline
Removed `PUBLIC_API_KEY` environment variable
The github secret value associated with this value should also be removed

BAU: Remove public Api key

---

lambdas/tests/unit/common/services/audit-service.test.ts

Audit service unit tests
unit test coverage
- [OJ-1195](https://govukverify.atlassian.net/browse/OJ-1195)
[OJ-1195]: https://govukverify.atlassian.net/browse/OJ-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1195 add audit service unit tests

---

lambdas/tests/unit/services/person-identity-service.test.ts

Person identity service unit tests
- [OJ-1205](https://govukverify.atlassian.net/browse/OJ-1205)
[OJ-1205]: https://govukverify.atlassian.net/browse/OJ-1205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1205 person identity service unit tests

---

lambdas/tests/unit/services/security/jwe-decrypter.test.ts

This is part of https://govukverify.atlassian.net/browse/OJ-1194 to add unit test coverage for typescript lambdas
Addresses ticket https://govukverify.atlassian.net/browse/OJ-1201
Added test coverage for JweDecrypter 
see above
- [OJ-1201](https://govukverify.atlassian.net/browse/OJ-1201
[OJ-1201]: https://govukverify.atlassian.net/browse/OJ-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1201: add test for jwe-decrypter

---

lambdas/src/services/auth-request-validator.ts
lambdas/tests/unit/services/auth-request-validator.test.ts

Unit test for Auth Request Validator - notice that the conditional have been adjust to return on first error. This is how the Java equivalent works as it throws as soon as something is wrong. Ideally we also want to throw as well. This PR is step towards this.
see: https://govukverify.atlassian.net/browse/OJ-1231
- [OJ-1224](https://govukverify.atlassian.net/browse/OJ-1224)
[OJ-1224]: https://govukverify.atlassian.net/browse/OJ-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1224: Add unit test for auth request validator

---

lambdas/src/common/utils/request-utils.ts
lambdas/src/handlers/authorization-handler.ts
lambdas/src/services/auth-request-validator.ts
lambdas/src/types/errors.ts
lambdas/tests/unit/common/utils/request-utils.test.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts
lambdas/tests/unit/services/auth-request-validator.test.ts

Instead of using generic Error this PR ensures the specification of a defined error type
the mirrors the java one see https://github.com/alphagov/di-ipv-cri-lib/blob/806c02d8beda586f301030b85b3a0d070a64bfd0/src/main/java/uk/gov/di/ipv/cri/common/library/error/ErrorResponse.java#L22
Instead of returning a ValidationResult and then inspecting it for which error to handle
throw the expected error and allow this to be handled by the catch block in the handler.
This aligns with pattern used in the access-token-handler
Stopped using ValidationResult, throw specific error
To ensure we handle errors, in a similar approach.
- [OJ-1231](https://govukverify.atlassian.net/browse/OJ-1231))
[OJ-1231]: https://govukverify.atlassian.net/browse/OJ-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

OJ-1231: use specific SessionValidationError

---

.github/workflows/pre-merge-checks-typescript.yml
lambdas/package.json

Add separate `prettier` task to GHA.
`eslitnt` is currently returning code violations, but `prettier` is already properly applied - so we should separate out these two tasks.

chore: Run pretter as separate linting task

---

lambdas/src/handlers/access-token-handler.ts
lambdas/src/services/bearer-access-token-factory.ts
lambdas/tests/unit/handlers/access-token-handler.test.ts
lambdas/tests/unit/services/bearer-access-token-factory.test.ts

Rename Service to Factory
Renamed the AccessTokenService to BearerAccessTokenFactory
AccessTokenService returns a bearerAccesstoken object

BAU: Rename AccessTokenService to BearerAccessTokenFactory

---

.github/workflows/post-merge-matrix-deploy.yml

Gradle needs to be pinned for the second batch of matrix deployments

fix: Pin gradle to 7.4.2 for post merge matrix workflow for build

---

lambdas/src/handlers/authorization-handler.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/services/security/jwe-decrypter.ts
lambdas/src/services/session-request-validator.ts
lambdas/src/services/session-service.ts
lambdas/src/types/errors.ts
lambdas/src/types/validation-result.ts
lambdas/tests/unit/handlers/session-handler.test.ts
lambdas/tests/unit/services/security/jwe-decrypter.test.ts
lambdas/tests/unit/services/session-request-validator.test.ts

Throw specific errors instead of returning a generic error result object, 
now error handling is done in manner consistent with the other handlers
Error handling in SessionHandler, aligned with the other handler
To allow a consist way of handling errors
- [OJ-1256](https://govukverify.atlassian.net/browse/OJ-1256)
[OJ-1256]: https://govukverify.atlassian.net/browse/OJ-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1256: throw specific sessionValidationerr

---

lambdas/tests/unit/services/auth-request-validator.test.ts

Change assertion style
Change assertion style from try-catch to expect-throw
Recommended improvement

OJ-1256: replace try catch style assertions in auth-request-validator test

---

lambdas/tests/unit/services/session-request-validator.test.ts

Change assertion style
Change assertion style from try-catch to expect-throw
Recommended improvement
- [OJ-1256](https://govukverify.atlassian.net/browse/OJ-1256)
[OJ-1256]: https://govukverify.atlassian.net/browse/OJ-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1256: Replace try catch assertion in session request validator test

---

lambdas/.eslintrc.js
lambdas/src/handlers/access-token-handler.ts
lambdas/src/handlers/authorization-handler.ts
lambdas/src/handlers/session-handler.ts
lambdas/tests/unit/common/config/config-service.test.ts
lambdas/tests/unit/handlers/access-token-handler.test.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts

To fix eslint no unsed vars some exemptions need to be made
Handlers require a second parameter; context, this is often unused 
by prefixing with _ i.e using `_context` exempts it from this eslint rule 
Also @decorator ie. `tracer` is just applied on some handlers but 
is not referred to, these are also exempt 
Addressing eslint warnings
- [Oj-1270](https://govukverify.atlassian.net/browse/Oj-1270)

Oj-1270: fix eslint no unused vars

---

lambdas/src/handlers/access-token-handler.ts
lambdas/src/handlers/authorization-handler.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/types/audit-event.ts
lambdas/tests/unit/common/config/config-service.test.ts
lambdas/tests/unit/common/security/jwt-verifier.test.ts
lambdas/tests/unit/handlers/access-token-handler.test.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts
lambdas/tests/unit/services/session-service.test.ts

This is part of fixing eslinting errors, in this case no-implicit-any warnings are addressed
A separate PR would looking into fix the use of any in the catch block of the lambda handler
which is not as straight for as the fixes here
Fix eslint warnings
Code improvements recommended by eslint rules
- [OJ-1270](https://govukverify.atlassian.net/browse/OJ-1270)

OJ-1270: fix eslint no implicit any part-1

---

.github/workflows/post-merge-matrix-deploy.yml
.secrets.baseline
README.md

This is an initial implementation of the non blocking matrix which implements fail-fast: false but does not prevent the corresponding build version of a failed deployment from attempting to run which will be added in another PR. This change also introduces switching of deployments on and off via setting repository variables, the default not to run if the corresponding variable is missing or set to false.
* The matrixes have had the fail-fast strategy set to false 
* An ENABLED matrix variable has been added for each job run which is set via repository variables
These changes have been made to:
* Prevent one CRI failure blocking the deployment for others
* Enable turning off of deployments without changing the workflow so that breaking changes can be controlled  
- …

feat: non blocking switchable matrix

---

lambdas/src/common/config/config-service.ts
lambdas/tests/unit/common/config/config-service.test.ts

config-service.ts
config-service.test.ts
The current implementation uses milliseconds when we need epoch seconds to match Java land. 
config-service.test.test changes include changing the expected ms result to seconds as that's what the dynamo db table expects. 
- [OJ-1624](https://govukverify.atlassian.net/browse/OJ-1624)

Oj 1624 epoch changes in config service

---

.github/workflows/post-merge-matrix-deploy.yml
.secrets.baseline

Added concurrency to the workflow
Fixed fraud build enablement variable name
Force continue with continue-on-error and always
Changed to prevent one CRI blocking another, to queue overlapping deployments and to fix incorrect variable 
- [OJ-1247](https://govukverify.atlassian.net/browse/OJ-1247)
[OJ-1247]: https://govukverify.atlassian.net/browse/OJ-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: force non-blocking and correct var name

---

lambdas/src/handlers/session-handler.ts
lambdas/src/services/session-request-validator.ts
lambdas/tests/unit/handlers/session-handler.test.ts
lambdas/tests/unit/services/session-request-validator.test.ts

Remove the error on missing shared claims
Add conditional logic to whether the personal identity information is saved
The error is not present in the Java lambda and was causing the address cri stub to error
The personal identity information cannot be saved without shared claims and would cause another error if attempted
The ticket to fix this and re-implement the TS error once the TS lamdbas have been released and are working in prod is here 
https://govukverify.atlassian.net/browse/OJ-1294
- [OJ-1285](https://govukverify.atlassian.net/browse/OJ-1285)
[OJ-1285]: https://govukverify.atlassian.net/browse/OJ-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1285 remove shared claims error and add conditional personal identity

---

.secrets.baseline
authorization/src/main/java/uk/gov/di/ipv/cri/common/api/handler/AuthorizationHandler.java
infrastructure/lambda/pre-merge-api.yaml
infrastructure/lambda/template.yaml
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
integration-tests/src/test/resources/features/AccessTokenAPI.feature
integration-tests/src/test/resources/features/AuthorizationAPI.feature
lambdas/jest.config.ts
lambdas/src/handlers/authorization-handler.ts
lambdas/src/handlers/create-auth-code-handler.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts

Remove the creation of [AuthCode ](https://github.com/alphagov/di-ipv-cri-common-lambdas/pull/57)in the AuthorizationCodeHandler 
see: https://github.com/alphagov/di-ipv-cri-common-lambdas/pull/57
The common lambda intergration test still require an AuthCode to be in the session table. In the normal code flow the responsibility lies with credential issuers this is still the case see [KBV](https://github.com/alphagov/di-ipv-cri-kbv-api/blob/main/lambdas/answer/src/main/java/uk/gov/di/ipv/cri/kbv/api/handler/QuestionAnswerHandler.java#L171) and [ADDRESS](https://github.com/alphagov/di-ipv-cri-address-api/blob/main/lambdas/address/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AddressHandler.java#L88)
An new [endpoint ](https://github.com/alphagov/di-ipv-cri-common-lambdas/blob/d8669fc3a …

Oj-1287: create authcode lambda for premerge

---

lambdas/src/common/security/jwt-verifier.ts
lambdas/tests/unit/common/security/jwt-verifier.test.ts

When using the TypeScript lambdas with core-stub they work fine, but coming in through the orchestrator stub there are issues.
The error message contains to
```
TypeError: \"alg\" argument is required when \"jwk.alg\" is not present
```
This suggests there is a difference in the signing key, which is overridable by config coming in via the authenticationAlg parameter
This PR defaults to the signing key alg, and falls back to the alg defined as a parameter
- [OJ-1286](https://govukverify.atlassian.net/browse/OJ-1286)
[OJ-1286]: https://govukverify.atlassian.net/browse/OJ-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: JWT verification issue due to JWK without alg

---

.github/workflows/post-merge-matrix-deploy.yml
.secrets.baseline

Passport CRI DEV and BUILD deployments configurations added to post-merge action
To align passport CRI with common-cri best practices
- [PLAT-805](https://govukverify.atlassian.net/browse/PLAT-805)
Secure pipeline secrets similar to existing CRIs 
[PLAT-805]: https://govukverify.atlassian.net/browse/PLAT-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLAT-805: Passport CRI in post-merge GHA

---

.github/workflows/post-merge-matrix-deploy.yml

The configure-aws-credentials action v1-node16 was failing due to a node12 reference which is no longer supported by GitHub. Version 2 has been released last week which resolves this issue. 
To fix the failing workflows
- [OJ-1346-](https://govukverify.atlassian.net/browse/OJ-1346)

fix: update configure-aws-credentials to v2

---

infrastructure/lambda/template.yaml
lambdas/src/handlers/access-token-handler.ts

This is a cleanup of the template.yml as well as making the code look as similar as possible
let see the impact of these changes
govuk journey id is missing for session and access token lambda not sure why
TS lambda not currently show all the expected journey id
- [OJ-1413](https://govukverify.atlassian.net/browse/OJ-1413)
[OJ-1413]: https://govukverify.atlassian.net/browse/OJ-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1413: govuk journey missing

---

lambdas/src/common/utils/errors.ts
lambdas/src/common/utils/power-tool.ts
lambdas/src/common/utils/request-utils.ts
lambdas/src/handlers/access-token-handler.ts
lambdas/src/handlers/authorization-handler.ts
lambdas/src/handlers/create-auth-code-handler.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/middlewares/access-token/validate-event-payload-middleware.ts
lambdas/src/middlewares/config/initialise-config-middleware.ts
lambdas/src/middlewares/error/error-middleware.ts
lambdas/src/middlewares/session/get-session-by-auth-code-middleware.ts
lambdas/src/middlewares/session/get-session-by-id.ts
lambdas/src/middlewares/session/set-gov-uk-signing-journey-id-middleware.ts
lambdas/src/services/auth-request-validator.ts
lambdas/src/services/security/jwe-decrypter.ts
lambdas/src/services/session-request-validator.ts
lambdas/src/services/session-service.ts
lambdas/src/services/token-request-validator.ts
lambdas/tests/unit/common/utils/request-utils.test.ts
lambdas/tests/unit/handlers/access-token-handler.test.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts
lambdas/tests/unit/handlers/session-handler.test.ts
lambdas/tests/unit/services/session-service.test.ts
lambdas/tests/unit/services/token-request-validator.test.ts

This is the 1st of a few more PR'S to go that uses middy as a way to ensure that `govuk_signin_journey_id` sticks around, when using `logger.appendkeys` since middy is middleware a series of middlewares are constructed to get the persisted id
This work uncovered a few gaps as well:
- the actual value used for the id was wrong is the session lambda, value used should be `clientSessionId` which come from  jwtPayload key of the name `govuk_signin_journey_id`
- Also we do not have the value require when retrieving the sessionItem via the `getSessionByAuthCode`
this is b'cos we a using a global index which exposes only (sessionId, redirectUri, clientId) ideally we want to expose the clientSessionId as well to get the `govuk_signin_journey_id` updating the global index is not straight forward …

Oj-1413: use middy in access token lambda

---

README.md
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java

This PR allow running integration test against localhost:8085 rather than the stub URL, this useful checking the if test pass local. Also introduced enviroment variable CRI_DEV so that the jwe can be produced with the expected audience type.
```
STACK_NAME=ola-kbv-cri-common CRI_DEV=kbv-cri-dev ENVIRONMENT=dev API_GATEWAY_ID_PRIVATE=3qstp8o17b IPV_CORE_STUB_BASIC_AUTH_USER=****** IPV_CORE_STUB_BASIC_AUTH_PASSWORD=********* IPV_CORE_STUB_URL="http://localhost:8085" DEFAULT_REDIRECT_URI="http://localhost:8085/callback"  gradle integration-tests:cucumber
```

BAU: Allow running Integration test on localhost

---

lambdas/src/handlers/access-token-handler.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/middlewares/access-token/validate-event-payload-middleware.ts
lambdas/src/middlewares/config/initialise-client-config-middleware.ts
lambdas/src/middlewares/config/initialise-config-middleware.ts
lambdas/src/middlewares/jwt/decrypt-jwe-middleware.ts
lambdas/src/middlewares/jwt/validate-jwt-middleware.ts
lambdas/src/middlewares/session/get-session-by-auth-code-middleware.ts
lambdas/src/middlewares/session/get-session-by-id.ts
lambdas/src/middlewares/session/set-gov-uk-signing-journey-id-middleware.ts
lambdas/src/types/jwe-request.ts
lambdas/tests/unit/handlers/access-token-handler.test.ts
lambdas/tests/unit/handlers/session-handler.test.ts

This is the 2nd PR that uses middy as a way to ensure that `govuk_signin_journey_id` sticks around, when using `logger.appendkeys` since middy is middleware a series of middlewares are constructed to get the persisted id
see: https://github.com/alphagov/di-ipv-cri-common-lambdas/pull/190  for the 1st PR
Things to note here:
Introduced `initialiseClientConfigMiddleware` which uses the client Id to retrieve configuration for both the session and access token hander
/{aws-common-stackname}/clients/ipv-core-stub/jwtAuthentication/redirectUri 
/{aws-common-stackname}/clients/ipv-core-stub/jwtAuthentication/publicSigningJwkBase64
/{aws-common-stackname}/clients/ipv-core-stub/jwtAuthentication/issuer
/{aws-common-stackname}/clients/ipv-core-stub/jwtAuthentication/authenticationAlg …

Oj-1413: use middy in access session lambda

---

lambdas/src/handlers/access-token-handler.ts
lambdas/src/handlers/authorization-handler.ts
lambdas/src/middlewares/session/get-session-by-id-middleware.ts
lambdas/tests/unit/handlers/access-token-handler.test.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts

This is the 3rd PR that uses middy as a way to ensure that `govuk_signin_journey_id` sticks around, when using logger.appendkeys since middy is middleware, a series of middlewares are constructed to get the persisted id
see: https://github.com/alphagov/di-ipv-cri-common-lambdas/pull/190 for the 1st PR
See https://govukverify.atlassian.net/browse/OJ-1413
- [OJ-1413](https://govukverify.atlassian.net/browse/OJ-1413)
[OJ-1413]: https://govukverify.atlassian.net/browse/OJ-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Oj-1413: use middy in authorization handler

---

lambdas/src/common/services/audit-service.ts
lambdas/tests/unit/common/services/audit-service.test.ts

see: [OJ-1435](https://govukverify.atlassian.net/browse/OJ-1435)
This PR changes this to be in seconds.
Audit timestamp changed to seconds
The Audit date is currently in milliseconds this is throwing off the txma reports.
- [OJ-1435](https://govukverify.atlassian.net/browse/OJ-1435)
[OJ-1435]: https://govukverify.atlassian.net/browse/OJ-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1435]: https://govukverify.atlassian.net/browse/OJ-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1435: Change audit date to seconds

---

lambdas/src/middlewares/jwt/decrypt-jwe-middleware.ts
lambdas/src/middlewares/jwt/validate-jwt-middleware.ts

The gov uk signing journey id does not currently appear, this PR introduce after hooks in the session handler for where the above logging appears to be missing.
Logging in the after hook of both the `decrypt-jwe-middleware.ts` and `validate-jwt-middleware.ts` ensures the journey signing id appears for when logging decryption of jwe and the validation jwt
Improvements

OJ-1439: Do logging in after hook of middleware

---

infrastructure/lambda/template.yaml

Switch dns mappings for di-ipv-cri-passport-api to review-pa from review-p
review-pa dns is now live
- [LIME-409](https://govukverify.atlassian.net/browse/LIME-409)
[LIME-409]: https://govukverify.atlassian.net/browse/LIME-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-409 Switch dns mappings for di-ipv-cri-passport-api to review-pa

---

README.md
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java

Allow running integration-test for common-lambda with the new AWS core stub
Made DEFAULT_CLIENT_ID into an environment variable instead of being hard coded
What to be able to run common-lambda integration test with new AWS core stub
- [OJ-1502](https://govukverify.atlassian.net/browse/OJ-1502)
[OJ-1502]: https://govukverify.atlassian.net/browse/OJ-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1502: Made DEFAULT_CLIENT_ID into an environment variable

---

.github/workflows/pre-merge-integration-test.yml
README.md
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java

Pre-merge-test to use AWS stub instead of PAAS stub
Move away from PAAS to AWS hosting of stub
PAAS would be decommission soon
- [OJ-1540](https://govukverify.atlassian.net/browse/OJ-1540)
Use of DEFAULT_CLIENT_ID to specify stub client id
[OJ-1533]: https://govukverify.atlassian.net/browse/OJ-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1540]: https://govukverify.atlassian.net/browse/OJ-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1540: Ensure integration test works with aws stubs

---

.github/workflows/post-merge-matrix-deploy.yml
.secrets.baseline

Added the Toy CRI DEV and BUILD to the matrix and updated to use the dev-platform upload action 
* The deployments are needed for the Toy CRI.
* The  Toy CRI has a full dev-platform stack which requires metadata for the hooks, the dev-platform upload action provides this metadata.
- [OJ-1516](https://govukverify.atlassian.net/browse/OJ-1516)
[OJ-1516]: https://govukverify.atlassian.net/browse/OJ-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

oj-1516 toy deployments plus dev-platform upload action

---

integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java

APISteps.java
* Use the Logger instead of `System.out.println` for better clarity of logs.
* Removed the use of `Optional.ofNullable` around the envs as `System.getenv()` will never be null so this call is redundant. Additionally, this removes the fallback of the PaaS URls which will eventually be decommissioned. 
- [OJ-1540](https://govukverify.atlassian.net/browse/OJ-1540)
[OJ-1540]: https://govukverify.atlassian.net/browse/OJ-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BAU: Use logger instead of System.out.println and no Optional on ENV

---

.github/workflows/post-merge-matrix-deploy-toy.yml
.secrets.baseline

* Added additional dev accounts to dev matrix
* Updated matrices workflows to be sequential with build second
* Removed consecutive parallel publish restrictions
* To better represent the overall design of the workflow
* Further improve performance
- [OJ-1581](https://govukverify.atlassian.net/browse/OJ-1581)
Existing workflow temporarily disabled from the GitHub console
Dev accounts and Toy build only
[OJ-1581]: https://govukverify.atlassian.net/browse/OJ-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci:update flow and add dev accounts

---

.secrets.baseline
infrastructure/lambda/template.yaml

Add CriVpcMapping for passport-v1 production
To allow common-api to deploy into passport-v1 production
- [LIME-619](https://govukverify.atlassian.net/browse/LIME-619)
[LIME-619]: https://govukverify.atlassian.net/browse/LIME-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-619 Add CriVpcMapping for passport-v1 production

---

infrastructure/lambda/template.yaml

Switch di-ipv-cri-passport-api to use di-devplatform-deploy values in dev environment
To allow common-api to deploy via pipline into passport-v1-dev
- [LIME-619](https://govukverify.atlassian.net/browse/LIME-619)
[LIME-619]: https://govukverify.atlassian.net/browse/LIME-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switch di-ipv-cri-passport-api to use di-devplatform-deploy values in dev

---

.secrets.baseline
deploy.sh
infrastructure/lambda/template.yaml
lambdas/.eslintignore
lambdas/src/handlers/audit-event-consumer-handler.ts
lambdas/tests/unit/handlers/audit-event-consumer.test.ts

Creation of a lambda to consume the audit events off the queue
To prevent txma being overwhelmed by the number of messages that performance testing will generate
- [OJ-1663](https://govukverify.atlassian.net/browse/OJ-1663)
[OJ-1663]: https://govukverify.atlassian.net/browse/OJ-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1663 Create audit event queue consumer lambda

---

infrastructure/lambda/template.yaml

sizing of deployment infrastructure in the cfn template
Updating build configuration to match production for the performance testing 
- [OJ-1654](https://govukverify.atlassian.net/browse/OJ-1654)
[OJ-1645]: https://govukverify.atlassian.net/browse/OJ-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1654]: https://govukverify.atlassian.net/browse/OJ-1654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

oj-1654 update scaling for performance testing

---

infrastructure/lambda/template.yaml

Updating the common lambdas so review-p is used as the VC issuer rather than review-pa
Updated the template to set the issuer for passport-api to review-p
So that when the new passport cri goes live the VCs issued are the same as the values expected by core and spot

LIME-802: Updating common lambdas for passport api so the issuer remains review-p

---

infrastructure/lambda/template.yaml

Update the audience to align with the review-p issuer and removed old references to preprod paas
Updated the audience to align with the review-p issuer and removed old references to preprod paas
To allow connection to core who expect issuer and audience to be the same

LIME-802: Updated passport audience and removed old references to the preprod url

---

infrastructure/lambda/template.yaml

Updated the Check HMRC mappings names
The deployments fail in build without the correct mappings
- [OJ-1931](https://govukverify.atlassian.net/browse/OJ-1931)
[OJ-1931]: https://govukverify.atlassian.net/browse/OJ-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

correct mappings for check hmrc

---

infrastructure/lambda/template.yaml

Added redirect mappings for HMRC Check and KBV
Redirect mappings are required for staging thru prod
- [OJ-1931](https://govukverify.atlassian.net/browse/OJ-1931)
- [OJ-1951](https://govukverify.atlassian.net/browse/OJ-1951)
- [IPS-306](https://govukverify.atlassian.net/browse/IPS-306)
- 
[OJ-1931]: https://govukverify.atlassian.net/browse/OJ-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1951]: https://govukverify.atlassian.net/browse/OJ-1951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-306]: https://govukverify.atlassian.net/browse/IPS-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

oj-1931 add mappings for HMRC API's

---

integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java

see: https://github.com/govuk-one-login/ipv-config/pull/1257
Fix: common-lambda integration test
Change default CRI_DEV environment value to new `common-lambda-dev`
B'cos common-lambda needs to run on `di-ipv-cri-dev` and also pre for when common-lambda has it's own account
defaulting to `Address-cri-dev` as before no longer makes sense
- [OJ-1994](https://govukverify.atlassian.net/browse/OJ-1994)
[OJ-1994]: https://govukverify.atlassian.net/browse/OJ-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-1994: Change CRI_DEV from Address-cri-dev to common-lambda-dev

---

.secrets.baseline
accesstoken/build.gradle
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/AccessTokenHandlerTest.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/utils/Injector.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/utils/MockHttpServer.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/utils/PreLambdaHandler.java
build.gradle

Added contract test for the accessTokenHandler API
This test mimics the session creation performed earlier in the journey and mocks out any calls to aws services
The test works by creating a fake api that can be called to simulate the call from the lambda to the api. This is based upon the original contract testing POC
This is the first step in putting together a contract testing suite between CRI Lime and IPV core

LIME-881: Setup contract test class for access token contract testing

---

.github/workflows/pre-merge-checks.yml
.secrets.baseline
accesstoken/build.gradle
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/AccessTokenHandlerTest.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/utils/Injector.java
build.gradle

Add connection to pact broker and split pact tests in to there own action
Included pact tests in the pre merge checks
To enable contract testing of resources prior to merging changes
- [LIME-882](https://govukverify.atlassian.net/browse/LIME-882)
- [ x] 3 Environment variables were added for the broker connection
[LIME-882]: https://govukverify.atlassian.net/browse/LIME-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-882: Added pact broker to the pact tests

---

infrastructure/lambda/template.yaml

`template.yaml` added a new `clientId` called `ipv-core-stub-aws-prod_3rdparty`
As part of the E2E strategy we are going to be using different clientId’s to determine which data source to use. As such, we need to register these clientId’s in common lambdas so that we don’t get any failures with auth/session.
- [OJ-2253](https://govukverify.atlassian.net/browse/OJ-2253)
[OJ-2253]: https://govukverify.atlassian.net/browse/OJ-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2253: Added `clientId` configuration for `ipv-core-stub-aws-prod_3rdparty`

---

infrastructure/lambda/template.yaml

Changed issuer and redirect URI for `ipv-core-stub-aws-build_3rdparty` to `https://cri-3rdparty.core.build.stubs.account.gov.uk`
There is a new instance of the core stub for `ipv-core-stub-aws-build_3rdparty` uses this URL for the issuer and redirect. As such, this needs to reflect otherwise we'll get errors when trying to use the `ipv-core-stub-aws-prod_3rdparty` client Id. 
- [OJ-2216](https://govukverify.atlassian.net/browse/OJ-2216)
[OJ-2216]: https://govukverify.atlassian.net/browse/OJ-2216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2216: Added client id `ipv-core-stub-aws-build_3rdparty`

---

build.gradle

JFrog subscription had expired so to unblock deployments we temporarily switched to mavenCentral
- [OJ-2257](https://govukverify.atlassian.net/browse/OJ-2257)
[OJ-2257]: https://govukverify.atlassian.net/browse/OJ-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2257: Bring back JFrog

---

infrastructure/lambda/template.yaml

Updated `IPVCore1RedirectURIMapping` for ipv-core to be nino.
Required for E2E testing and the current value was out of date. Core have confirmed they use `nino` as the ID
- [OJ-2272](https://govukverify.atlassian.net/browse/OJ-2272)
[OJ-2272]: https://govukverify.atlassian.net/browse/OJ-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2272: Updated  `RedirectURI` for ipv-core

---

lambdas/src/handlers/access-token-handler.ts
lambdas/src/services/session-service.ts
lambdas/tests/unit/services/session-service.test.ts

Renamed `createAccessTokenCode` to `createAccessTokenCodeAndRemoveAuthCode`
Method name does not reflect what its actually doing which caused confusion on system behaviour. 
- [OJ-2379](https://govukverify.atlassian.net/browse/OJ-2379)
[OJ-2379]: https://govukverify.atlassian.net/browse/OJ-2379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2379: Renamed `createAccessTokenCode` to `createAccessTokenCodeAndRemoveAuthCode`

---

integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/resources/features/AuthorizationAPI.feature
lambdas/src/common/utils/errors.ts
lambdas/src/handlers/authorization-handler.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts

Added the access_denied step definitions within the AuthorizationAPI feature file and the associated step definitions file. We updated the authorisation handler in TS to include 403 access denied response.
The tests were required to test the functionality of the /authorisation endpoint as per ticket OJ-2346
[OJ-2346](https://govukverify.atlassian.net/browse/OJ-2346)
[OJ-2346]: https://govukverify.atlassian.net/browse/OJ-2346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2346 Updated and added tests for 403 on authorisation endpoint

---

integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
lambdas/src/common/utils/errors.ts
lambdas/tests/unit/handlers/authorization-handler.test.ts

- Remove references to PAAS environment which was decommissioned a while ago
- Minor refactoring
Stubs have been deployed to AWS for a while now
No longer relevant to have details about PAAS
- [OJ-2441](https://govukverify.atlassian.net/browse/OJ-2441)
[OJ-2441]: https://govukverify.atlassian.net/browse/OJ-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2441: remove pass environment references

---

README.md

see: https://govukverify.atlassian.net/jira/software/c/projects/OJ/boards/502?selectedIssue=OJ-2441
see: https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/282
Removed references to PAAS environment which was decommissioned a while ago
Stubs are now AWS

OJ-2441: updated instructions in README.md

---

.github/workflows/check-pr.yml
.github/workflows/run-pact-tests.yml
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/AccessTokenHandlerTest.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/utils/MockHttpServer.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/utils/PreLambdaHandler.java
integration-tests/build.gradle

Enabled contract testing in the common lambdas for the passport cri access token
To enable contract testing as a pre-merge step

LIME-989: Enabling contract testing for passport

---

README.md
lambdas/README.md
lambdas/src/common/security/jwt-verifier.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/services/evidence_request.ts
lambdas/src/services/session-request-validator.ts
lambdas/src/services/session-service.ts
lambdas/src/types/session-request-summary.ts
lambdas/tests/unit/services/session-request-validator.test.ts

Added `evidence_requested` details into the session table because ipv-core now sends `evidence_requested` within the signed JAR payload. This has superseded the `scope` value that was provided however this was not used in common-lambda.
- [OJ-2453](https://govukverify.atlassian.net/browse/OJ-2453)
[OJ-2453]: https://govukverify.atlassian.net/browse/OJ-2453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2453: Add `evidence_requested` to session from JAR request

---

infrastructure/lambda/template.yaml
lambdas/src/services/session-request-validator.ts
lambdas/tests/unit/services/session-request-validator.test.ts

Updated the session-request-validator to check if the strengthScore is 2 within the `evidence_requested` field for the NINO CRI.
- [OJ-2453](https://govukverify.atlassian.net/browse/OJ-2453)
[OJ-2453]: https://govukverify.atlassian.net/browse/OJ-2453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2453 validate strength score

---

infrastructure/lambda/template.yaml
lambdas/src/common/config/config-service.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/middlewares/config/initialise-client-config-middleware.ts
lambdas/src/services/session-request-validator.ts
lambdas/src/types/config-keys.ts
lambdas/src/types/evidence-requested-config.ts
lambdas/tests/unit/common/config/config-service.test.ts

Related to: https://govukverify.atlassian.net/browse/OJ-2524
Do evidence mapping in common-lambda template instead of hard-coding in session validator
It would make it easier to add evidence mapping for other CRI's when needed
The mapping for evidence request moved from code to common lambda
template. Here each CRI using common lambda would provide it's
strengthScore value through a mapping i.e.
```
EvidenceRequestedMapping:
di-ipv-cri-check-hmrc-api:
strengthScore: 2
di-ipv-cri-dl-api:
strengthScore: 3
```
then the value can be retrieved through the corresponding parameter
```
EvidenceRequestedStrengthScoreParameter:
Type: AWS::SSM::Parameter
Properties:
Name: !Sub "/${CriIdentifier}/strengthScore"
Type: String
Value: !FindInMap [ EvidenceRequestedMapping, !Ref CriIdentifier, …
```

OJ-2524 evidence req in config

---

infrastructure/lambda/template.yaml
lambdas/src/common/config/config-service.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/middlewares/config/initialise-client-config-middleware.ts
lambdas/src/types/config-keys.ts
lambdas/tests/unit/common/config/config-service.test.ts
lambdas/tests/unit/handlers/session-handler.test.ts

In addition to the work done as part of  to include information useful to the Fraud and Analytics teams, an extensions.evidence.context field should be included in the IPV_HMRC_RECORD_CHECK_CRI_START event to indicate whether the NINO CRI was initiated for a identity check
Implementation of a record_check in the start event is out of scope for this ticket
Added context to START_EVENT
- [OJ-2524(https://govukverify.atlassian.net/browse/OJ-2524)

OJ-2524: add context to start event

---

.github/workflows/deploy-branch.yml
deploy.sh
infrastructure/lambda/template.yaml

These are created by the TxMA stack in the common-infra repo instead (govuk-one-login/ipv-cri-common-infrastructure#92).
- Use the prefixed TxMA exports as the non-prefixed versions are deprecated
- Don't set default parameter values in the deploy script when those values are already the defaults in the template

OJ-2546: Remove mock TxMA queue resources from the SAM template

---

.secrets.baseline
lambdas/src/services/person-identity-service.ts
lambdas/tests/unit/services/person-identity-service.test.ts

Correct TTL in person-identity-service.ts
TTL was inadvertently set to the raw value of the expiry window (7200/2hrs), instead of the calculated expiry time.
- [LIME-1161](https://govukverify.atlassian.net/browse/LIME-1161)
[LIME-1161]: https://govukverify.atlassian.net/browse/LIME-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1161 Correct TTL in person-identity-service.ts

---

infrastructure/lambda/template.yaml

CSLS was disabled for check-hmrc-cri-api so there was no common lambda logs going to Splunk.

BAU: Enable CSLS for check-hmrc-api

---

infrastructure/lambda/template.yaml

Added CSLS Dest arn condition to allow check-hmrc to use the new csls destination arn.
Looging to Splunk was broken for check-hmrc
- [OJ-2645](https://govukverify.atlassian.net/browse/OJ-2645)
[OJ-2645]: https://govukverify.atlassian.net/browse/OJ-2645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2645: New CSLS arn added for use by check-hmrc

---

infrastructure/lambda/template.yaml
lambdas/src/common/config/config-service.ts
lambdas/src/handlers/session-handler.ts
lambdas/src/middlewares/config/initialise-client-config-middleware.ts
lambdas/src/services/cri_evidence_properties.ts
lambdas/src/services/session-request-validator.ts
lambdas/src/types/config-keys.ts
lambdas/src/types/evidence-requested-config.ts
lambdas/tests/unit/common/config/config-service.test.ts
lambdas/tests/unit/handlers/session-handler.test.ts
lambdas/tests/unit/services/session-request-validator.test.ts

- Added the use of an optional CRIEvidenceProperties parameter to validate evidence requested values. 
- Removed the strengthScore parameter for all CRIs (now included in the CRIEvidenceProperties)
- Added verificationScore validation to the session-request-validator
- Modified config service parameter retrieval to only log if the CRIEvidenceProperties parameter is not found
- Added tests for the verificationScore validation. 
- Refactor some of the tests
I want the system to support a Low Confidence journey for kbv by validating a verification score of 1 &  2 in the EvidenceRequest from ipv-core.
- [OJ-2641](https://govukverify.atlassian.net/browse/OJ-2641)
[OJ-2641]: https://govukverify.atlassian.net/browse/OJ-2641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

OJ-2641: Support multiple scores for cri

---

.github/dependabot.yml

Adds gradle scanning to dependabot as per the [recommended implementation from team manual](https://team-manual.account.gov.uk/development-standards-processes/coding-practices-and-processes/dependabot/#meeting-development-standards)
Note this is a copy of PR https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/286

Adds gradle scanning to dependabot

---

.github/workflows/deploy-branch.yml
.gitignore
accesstoken/build.gradle
accesstoken/src/main/java/uk/gov/di/ipv/cri/common/api/handler/AccessTokenHandler.java
accesstoken/src/test/java/uk/gov/di/ipv/cri/common/api/handler/pact/AccessTokenHandlerTest.java
authorization/build.gradle
authorization/src/main/java/uk/gov/di/ipv/cri/common/api/handler/AuthorizationHandler.java
authorization/src/main/java/uk/gov/di/ipv/cri/common/api/service/AuthorizationValidatorService.java
build.gradle
session/build.gradle
session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
session/src/main/java/uk/gov/di/ipv/cri/common/api/service/KMSRSADecrypter.java
session/src/main/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestService.java

Update to CRI Lib 3.0.1 and switch to using new constructors for services and reusing clients via ClientProviderFactory.
AWS SDK 2.20.162 -> 2.26.16 (version now set via dependencies variable)
New Aws Crt Http Client aligned with AWS SDK 2.26.16 AWS Lambda Events 3.11.0 -> 3.11.6
AWS Lambda Powertools 1.12.3 -> 1.18.0
Nimbusds Oauth 11.2 -> 11.4
Jackson 2.13.1 -> 2.15.2
Removes unused dependencies in the Jackson configuration.
Remove versions specified for the main Jackson dependencies and defer to the ones pull in from software.amazon.awss
dk:bom.
There is a breakage in a later jackson version, which crashes in the sdk classes which expect the older versions.
Note : jackson-datatype-jsr310 and jackson-datatype-jdk8 are not in the aws sdk and are custom dependencies these version have …

LIME-1071 Update to CRI Lib 3.0.1 and align with service changes.

---

lambdas/src/handlers/session-handler.ts
lambdas/tests/unit/handlers/session-handler.test.ts

Added evidence_requested object to the START audit event, this includes the verificationScore so we can see the requested journey for kbv
To ensure the TxMA events for the Experian KBV API include the correct verification score and evidence requested,
- [OJ-2621](https://govukverify.atlassian.net/browse/OJ-2621)
[OJ-2621]: https://govukverify.atlassian.net/browse/OJ-2621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2621: Added evidence_requested object to the START audit event

---

lambdas/package-lock.json
lambdas/package.json
lambdas/src/common/config/config-service.ts

Remove aws-sdk devDep
AWS has announced that AWS SDK for JavaScript v2 will enter maintenance mode on September 8, 2024
- [OJ-2661](https://govukverify.atlassian.net/browse/OJ-2661)
[OJ-2661]: https://govukverify.atlassian.net/browse/OJ-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2661: Remove aws-sdk devDep

---

infrastructure/lambda/template.yaml

As part of ensuring we are properly configured for `pre-prod`
see: https://govukverify.atlassian.net/browse/OJ-2769
ipv-core uses nino to identify Check-hmrc
Wrong id value as can be confirmed 
corresponding configuration can be found [here](https://github.com/govuk-one-login/ipv-core-common-infra/blob/main/utils/config-mgmt/app/configs/core.production.params.yaml#L320):

OJ-2769: Update client callback url param identifier to nino

---

infrastructure/lambda/template.yaml

Set IsCSLSDisabled to true for the common account
The stack is failing to deploy to the `di-ipv-cri-common-build` account because of the error
```
Resource handler returned message: "User with accountId: 667736788427 is not authorized to perform: 
logs:PutSubscriptionFilter on resource: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython 
(Service: CloudWatchLogs, Status Code: 400, Request ID: 1f88ba51-69c6-420b-8d42-ed88b504c155)" 
(RequestToken: 1c829f56-384b-c463-74bb-2b8758f16180, HandlerErrorCode: AccessDenied)
```
I can't see that in the last year we've had logs for the `di-ipv-cri-toy-api` CRI in Splunk and as this only exists for dev/build I don't think we need the logs going to Splunk.

Set IsCSLSDisabled for the common account

---

lambdas/src/handlers/session-handler.ts
lambdas/tests/unit/handlers/session-handler.test.ts

The "extensions" object in the START event is updated to use `evidence` as an array
DAP had problems with processing extensions object since the evidence block in other audit events is normally an array.
- [OJ-2785](https://govukverify.atlassian.net/browse/OJ-2785)
[OJ-2785]: https://govukverify.atlassian.net/browse/OJ-2785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2785: Fix - Update evidence object to use array

---

package-lock.json
test-resources/test-harness/infrastructure/public-api.yaml
test-resources/test-harness/infrastructure/samconfig.toml
test-resources/test-harness/infrastructure/template.yaml

Created a new endpoint called `/events` which allows you to query the "audit events table".
There is also a new domain name associated with this endpoint in the format:  `<stackName>.<Environment>.account.gov.uk/` e.g. `https://test-resources.review-hc.dev.account.gov.uk/`
This events API takes 2 query string parameters; partitionKey and sortKey. 
To support the test strategy with the test harness approach. 
Sample API output:
```
[{"sortKey":{"S":"TXMA#IPV_HMRC_RECORD_CHECK_CRI_START#1726084120#69de99e1-7a75-4abf-b355-7b9e3c3c52b9"},"event":{"S":"{\"component_id\":\"https://review-hc.dev.account.gov.uk\",\"event_name\":\"IPV_HMRC_RECORD_CHECK_CRI_START\",\"extensions\":{\"evidence\":{\"context\":\"identity_check\"}},\"restricted\":{\"device_information\":{\"encoded\":\"eyJhdWRpdF9oZWFkZXJ …
```

OJ-2736: `/events` endpoint

---

build.gradle
session/src/main/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestService.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestServiceTest.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SignedJWTBuilder.java

To retrieve the context claim (if present) from the JAR and store in the session.
To allow context to be passed through to the CRI. 
- [OJ-2812](https://govukverify.atlassian.net/browse/OJ-2812)
[OJ-2812]: https://govukverify.atlassian.net/browse/OJ-2812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2812: Add context claim to session if present in JAR

---

.github/workflows/check-pr.yml
.github/workflows/package-common-lambdas.yml
.github/workflows/package-test-resources.yml
.github/workflows/run-integration-tests.yml
.github/workflows/run-pact-tests-java.yml
.github/workflows/run-pact-tests-ts.yml

- Exclude test resources from the workflow that publishes common lambdas
- Adjust naming and formatting
- Add concurrency to jobs and workflows

OJ-2738: Don't deploy common lambdas on changes to test resources

---

lambdas/src/handlers/session-handler.ts
lambdas/src/services/session-service.ts
lambdas/src/types/session-request-summary.ts
lambdas/tests/unit/handlers/session-handler.test.ts
lambdas/tests/unit/services/session-service.test.ts

context can now be included as in the JWT for a session. This now gets context from the JWT and stores it within the session item.
We want to make the corresponding changes as in the Java lambdas to store context from the JWT.
Note: check-hmrc determines the "context" of a record_check or an identity_check through the presence of the evidence_requested property. This PR allows an actual context property to be included in the JWT and stored in the session item. If this property is used in the future and wants to be included in the audit event, check-hmrc "context" logic may need refactoring. 
- [OJ-2815](https://govukverify.atlassian.net/browse/OJ-2815)
Tested with a check-hmrc stack through the core stub.
[OJ-2815]: https://govukverify.atlassian.net/browse/OJ-2815?atlOrigin=eyJpIjoiNWRkNTl …

OJ-2815: Update TS session-handler to store context

---

.github/workflows/run-unit-tests-java.yml
.github/workflows/run-unit-tests-ts.yml
.github/workflows/scan-repo.yml

EOL on the 5th December 2024
Also updated version of Sonar Cloud as it needs to use download-artifact v4 as well
https://govukverify.atlassian.net/browse/PSREDEV-1911
https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new
Updated a GH action
V3 being EOLed 5th Dec
https://govukverify.atlassian.net/browse/PSREDEV-1911

Updated to version 4 of upload artifact action

---

build.gradle
infrastructure/lambda/pre-merge-api.yaml
infrastructure/lambda/template.yaml

- Non Alias permissions need to be kept until all CRI's migrate to snap-start.
- SnapStartMapping added to enable a controlled role out per env for each CRI
Alias add as a technical requirement of snap-start.
SnapStartMapping 
Added to enable snap-start role out only to specific CRI and environments.
And so that greater testing can happen prior to production role-out for each CRI.
- [LIME-1384](https://govukverify.atlassian.net/browse/LIME-1384)
[LIME-1384]: https://govukverify.atlassian.net/browse/LIME-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1384 - Add SnapStart Alias and Permissions

---

infrastructure/lambda/template.yaml

Enable snap-start for Passport CRI (dev-staging)
To test snap-start prior to production roll out
- [LIME-1437](https://govukverify.atlassian.net/browse/LIME-1437)
[LIME-1437]: https://govukverify.atlassian.net/browse/LIME-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1437 Enable snap-start for Passport CRI (dev-staging)

---

infrastructure/lambda/template.yaml

Enable SnapStart on the common-api Java Lambdas for Passport CRI
SnapStart is enabled from dev through staging, this enables it for integration and production on the common-api lambdas.
- [LIME-1521](https://govukverify.atlassian.net/browse/LIME-1521)
[LIME-1519]: https://govukverify.atlassian.net/browse/LIME-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1520]: https://govukverify.atlassian.net/browse/LIME-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1521]: https://govukverify.atlassian.net/browse/LIME-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1521 Passport CRI enable SnapStart in common-api lambdas

---

infrastructure/lambda/template.yaml

Enable ProvisionedConcurrency on Java Lambdas for Fraud CRI
ProvisionedConcurrency is enabled on the main Fraud CRI lambdas but not on the common-api lambdas.
- [LIME-1519](https://govukverify.atlassian.net/browse/LIME-1519)
[LIME-1519]: https://govukverify.atlassian.net/browse/LIME-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1519 Fraud CRI - enable ProvisionedConcurrency on Java Lambdas

---

.github/workflows/clean-up-deployments.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-branch.yml
.github/workflows/scan-repo.yml

Some nested actions (upload & download-artifact v3) have been deprecated and were nested inside [govuk-one-login/github-actions](https://github.com/govuk-one-login/github-actions). Updates to use the latest commits for each action using commit `cf644c0d66c41259bfe2509852d1211e3f01f44d`
Build SAM App failing.
`Error: This request has been automatically failed because it uses a deprecated version of actions/upload-artifact: v3. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ `

BAU: Bump github-actions versions so deprecated actions no longer used

---

lambdas/package.json
package-lock.json
test-resources/package.json

Bump version 0.17 -> 0.25 to resolve security vulns.
Resolves https://github.com/govuk-one-login/ipv-cri-common-lambdas/security/dependabot/47
Resolves https://github.com/govuk-one-login/ipv-cri-common-lambdas/security/dependabot/48
- [OJ-3003](https://govukverify.atlassian.net/browse/OJ-3003)
[OJ-3003]: https://govukverify.atlassian.net/browse/OJ-3003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3003: Bump esbuild

---

.github/workflows/scan-repo.yml

Update sonar GHA to the latest commit SHA.
Upstream sonar action is being deprecated.
- [OJ-3048](https://govukverify.atlassian.net/browse/OJ-3048)
[OJ-3048]: https://govukverify.atlassian.net/browse/OJ-3048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3048: Update sonar action

---

test-resources/deploy.sh

Added `deploy.sh` for test resources stack
Easier deployments of localdev test-resources stacks. 
- [OJ-2331](https://govukverify.atlassian.net/browse/OJ-2331)
[OJ-2331]: https://govukverify.atlassian.net/browse/OJ-2331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2331: Add deploy script for test resources stack

---

lambdas/src/services/token-request-validator.ts
lambdas/tests/unit/services/token-request-validator.test.ts

Thanks to Coral Gage, there was a wrong error being thrown when the client_assertion_type is not present
or is of the wrong value

OJ-3113: Fix wrong client assert type

---

infrastructure/lambda/template.yaml

Added a new clientId called ipv-core-stub-aws-headless
To support headless core stub
- [OJ-2331](https://govukverify.atlassian.net/browse/OJ-2331)
[OJ-2331]: https://govukverify.atlassian.net/browse/OJ-2331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create ipv-core-stub-aws-headless clientId

---

test-resources/deploy.sh
test-resources/infrastructure/samconfig.toml
test-resources/infrastructure/template.yaml

Implement DequeueEvents condition
So that local dev stacks don't dequeue events from the main txma event queue that is used for pre-merge testing
- [OJ-3120](https://govukverify.atlassian.net/browse/OJ-3120)
[OJ-3120]: https://govukverify.atlassian.net/browse/OJ-3120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3120: Implement DequeueEvents condition

---

.github/workflows/clean-up-deployments.yml

Update clean up stacks to include all preview stacks
So that test resources stacks are also cleaned up 
- [OJ-3122](https://govukverify.atlassian.net/browse/OJ-3122)
[OJ-3122]: https://govukverify.atlassian.net/browse/OJ-3122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3122: Update clean up stacks to include all preview stacks

---

test-resources/infrastructure/template.yaml

The pipeline for Experian KBV and Address CRI broke because there is no protected subnet,  Protected subnet is required
for /callback to be able to make calls successfully to public CRI endpoints like /token and /credential/issue
Headless core stub would need to be able to call public endpoint irrespective of what the CRI is
- [OJ-3128](https://govukverify.atlassian.net/browse/OJ-3128)
[OJ-3128]: https://govukverify.atlassian.net/browse/OJ-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3128: conditionally add protected subnet

---

.secrets.baseline
package-lock.json
test-resources/headless-core-stub/README.md
test-resources/headless-core-stub/lambdas/start/package.json
test-resources/headless-core-stub/lambdas/start/src/errors/error-response.ts
test-resources/headless-core-stub/lambdas/start/src/errors/headless-core-stub-error.ts
test-resources/headless-core-stub/lambdas/start/src/services/jwt-claims-set-service.ts
test-resources/headless-core-stub/lambdas/start/src/services/signing-service.ts
test-resources/headless-core-stub/lambdas/start/src/start-handler.ts
test-resources/headless-core-stub/lambdas/start/src/types/claims-set-overrides.ts
test-resources/headless-core-stub/lambdas/start/src/types/jwt-claims-set.ts
test-resources/headless-core-stub/lambdas/start/tests/errors/error-response.test.ts
test-resources/headless-core-stub/lambdas/start/tests/services/jwt-claims-set-service.test.ts
test-resources/headless-core-stub/lambdas/start/tests/services/signing-service.test.ts
test-resources/headless-core-stub/lambdas/start/tests/start-handler.test.ts
test-resources/headless-core-stub/utils/tests/crypto/signer.test.ts
test-resources/headless-core-stub/utils/tests/test-data.ts
test-resources/headless-core-stub/utils/tsconfig.json
test-resources/infrastructure/public-api.yaml
test-resources/infrastructure/template.yaml
test-resources/package.json

- Added `/start` endpoint to the test-resources stack. 
We want a headless, typescript core stub that has a /start endpoint that returns a JWT that can be used to start a session in any CRI frontend.
- [OJ-2331](https://govukverify.atlassian.net/browse/OJ-2331)
[OJ-2331]: https://govukverify.atlassian.net/browse/OJ-2331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2331: Add start endpoint to headless-core-stub

---

README.md
test-resources/infrastructure/public-api.yaml
test-resources/infrastructure/template.yaml

We are now using `AWS::ApiGateway::RestApi` for the APIGateway
We have created a headless core stub but there is an explicit deny defined in the OpenAPI spec which means any request to the `/callback` endpoint will not work unless it was called from within the account. 
The deny was added for the `/events` endpoint but now that we have introduced more endpoints that should not be denied, we have updated the API definition to be a `AWS::ApiGateway::RestApi`. 
The reason this has been done is because on a `AWS::ApiGateway::RestApi` you can add endpoint specific policies, in this case, we deny everyone on the /events endpoint but allow the rest. 
In the case of the `/start` endpoint - this will still require sigv4 authentication.

Change APIGateway into a AWS::ApiGateway::RestApi

---

README.md
test-resources/headless-core-stub/lambdas/callback/src/callback-handler.ts
test-resources/headless-core-stub/lambdas/callback/tests/callback-handler.test.ts

Changed the content type for /callback to text/plain
Browser is trying to download the file as opposed to viewing it.

feat: change content type to text/plain for headless /callback

---

test-resources/headless-core-stub/lambdas/start/src/services/jwt-claims-set-service.ts

Changed Math.round to `Math.floor`
Integration test validate the JWT returned from the start endpoint and are failing as the `nbf` can sometimes be in the future due to using `Math.round`.

Fix: Test Resources - Round down time based JWT values

---

build.gradle
deploy.sh
infrastructure/lambda/template.yaml
session/src/main/java/uk/gov/di/ipv/cri/common/api/service/KMSRSADecrypter.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/service/KMSRSADecrypterTest.java

- Introduced logic to decrypt JWE content using primary, secondary, and previous key aliases behind a feature toggle.
- Added a fallback mechanism to attempt decryption with the secondary and previous aliases if the primary alias fails during execution of the key rotation step function.
- Added unit test cases to verify decryption using each key alias, including fallback scenarios.
The KMSRSADecrypter has been updated to support the use of KMS aliases for decryption. This change is required for the key rotation pilot in Passport CRI.
- [LIME-1592](https://govukverify.atlassian.net/browse/LIME-1592)
[LIME-1592]: https://govukverify.atlassian.net/browse/LIME-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1592 Added support for key rotation 

---

.gitignore
deploy.sh
infrastructure/lambda/template.yaml

Add new ipv-core client id - "ipv-core-3rd-party-stubs"
- Added .npmrc to .gitignore to mitigate leaking github tokens should .npmrc be located in the repo
- - Pre-commit uses the event catalog npm package which needs a token to install
- Unable to deploy into dev via deploy.sh
ipv-core-3rd-party-stubs - To enable an IPV-Core end to end journey with CRI using third-party stubs
.npmrc to .gitignore - Pre-commit uses the event catalog npm package which needs a token to instal. To avoid leaking this should this be added to a repo based .npmrc
"localdev" changed to "dev" as this prevents deploying into dev via deploy.sh
- [LIME-1626](https://govukverify.atlassian.net/browse/LIME-1626)
[LIME-1626]: https://govukverify.atlassian.net/browse/LIME-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

LIME-1626 Add new ipv-core client id - "ipv-core-3rd-party-stubs"

---

.github/workflows/deploy-branch.yml
.github/workflows/test-resources-preview.yml

Unpin sam version from preview stack. 
Reverts https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/389 but keeps the newer version of the action.
No longer requires pinning as the linting bug was fixed in Sam CLI 1.135.0 which ubuntu-latest image now uses.
- [OJ-3049](https://govukverify.atlassian.net/browse/OJ-3049)
[OJ-3049]: https://govukverify.atlassian.net/browse/OJ-3049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3049: Unpin sam-version from preview action

---

infrastructure/lambda/template.yaml

Disabling Provisioned Concurrency (This PR must be merged before enabling snapstart - https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/444)

LIME-1441 - disabling provisionedConcurrency for DL (dev-staging)

---

infrastructure/lambda/template.yaml

Enable SnapStart on the common-api Java Lambdas for DL CRI
SnapStart is enabled from dev through staging, this enables it for integration and production on the common-api lambdas.
- [LIME-1443](https://govukverify.atlassian.net/browse/LIME-1443)
[LIME-1443]: https://govukverify.atlassian.net/browse/LIME-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1443 DL CRI enable SnapStart in common-api lambdas - integration/production

---

session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
session/src/main/java/uk/gov/di/ipv/cri/common/api/service/KMSRSADecrypter.java
session/src/main/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestService.java
session/src/test/java/uk/gov/di/ipv/cri/common/api/service/KMSRSADecrypterTest.java

Implement an alarm when no key alias available to the CRI that matches the encryption key used to create the encrypted payload. 
- Updated KMSRSADecrypter with new metric 
- Required event probe to be added to Session handler and Service
- Unit tests amended to include event probe mock
- [LIME-1630](https://govukverify.atlassian.net/browse/LIME-1630)
[LIME-1630]: https://govukverify.atlassian.net/browse/LIME-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1630 Added metric for Oauth alias decryption failure

---

infrastructure/lambda/template.yaml

Disabled Provisioned Concurrency for Fraud, this PR should be merged before the fast follow which enables snapstart - https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/453

LIME-1622 - disabling provisioned concurrency (build/staging)

---

build.gradle
infrastructure/lambda/template.yaml

bump cri-lib to 5.0.0
set `ENV_VAR_FEATURE_CONSUME_PUBLIC_JWK` environment variable for token and session lambda
set `PUBLIC_JWKS_ENDPOINT ` environment variable for token and session lambda
So that we can use cores public JWK endpoint
This is only going to be abled for address-cri and if you want to add other CRIs, you have to append to `KeyRotationEnabled` and `JwkEndpoint` mapping with the cri identifier. 
- [OJ-2972](https://govukverify.atlassian.net/browse/OJ-2972)
[OJ-2972]: https://govukverify.atlassian.net/browse/OJ-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: set environment variables to use key rotation

---

infrastructure/lambda/template.yaml

Enabling snapstart, this PR should be a fast follow to disabling provisioned concurrency for Fraud - https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/452

LIME-1622 - enabling snapstart (build/staging)

---

test-resources/headless-core-stub/lambdas/mock-jwks/src/mock-jwk-handler.ts
test-resources/infrastructure/public-api.yaml

Removed the `responseParameters` because AWS_PROXY integration type ignores responseParameters, so the headers defined here were not being set. The header is now being returned by the Lambda directly. 
Removed the other headers inside responseParameters as they are not needed. 
**Screenshot**

fix-cache-control-header

---

build.gradle
infrastructure/lambda/template.yaml

cri-lib to 5.0.1 contains a NPE fix
disabled public jwk consumption in higher envs as [OJ-3196](https://govukverify.atlassian.net/browse/OJ-3169)
- [OJ-2972](https://govukverify.atlassian.net/browse/OJ-2972)
[OJ-2972]: https://govukverify.atlassian.net/browse/OJ-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-2972: bump cri-lib and disable public jwk consumption in > dev for address

---

test-resources/infrastructure/template.yaml

AWS::ApiGateway::RestApi does not auto redeploy when the OpenAPI spec was updated. This meant we have to manually redeploy which causes friction.

feat: use AWS::Serverless::API instead of AWS::ApiGateway::RestApi

---

test-resources/infrastructure/template.yaml

Reverts govuk-one-login/ipv-cri-common-lambdas#461
Because it is now unable to create a stage, error "stage already exists"

Revert "feat: use AWS::Serverless::API instead of AWS::ApiGateway::RestApi"

---

infrastructure/lambda/template.yaml

Enable consumption of the public JWK endpoint in address build/staging
It has been tested in dev and works so we are now ready to test in build/staging
- [OJ-2972](https://govukverify.atlassian.net/browse/OJ-2972)
[OJ-2972]: https://govukverify.atlassian.net/browse/OJ-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: key rotation enabled for build/staging

---

infrastructure/lambda/template.yaml

This PR is to disable provisioned concurrency for frauds common-lambdas, there will be a fast follow PR to enable snapstart - https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/467

LIME-1447 - disabling provisioned concurrency (int/prod)

---

infrastructure/lambda/template.yaml
lambdas/src/common/security/jwt-verifier.ts
lambdas/src/types/jwks.ts
lambdas/tests/unit/common/security/jwt-verifier.test.ts

JWT verifying will now attempt to retrieve the JWKS from a endpoint. This is configured through the `ENV_VAR_FEATURE_CONSUME_PUBLIC_JWK` & `PUBLIC_JWKS_ENDPOINT` environment variables.
Otherwise, it will continue to use the SSM param. Fallback logic is also implemented, so if the JWKS endpoint fails for any reason it will attempt to use the parameters.
The JWKS endpoint response will be cached for as long as returned int the Cache-Control header returned in the JWKS endpoint response.
It has only been enabled for Experian KBV dev.
*Note for Reviewing: I have not changed the `JWKS Param` unit tests, I've just wrapped them in a new describe. GitHub seems to have picked them all up as changed code.
When the Session lambda receives a JWT from core it needs to verify the signature using the …

OJ-3077: Add JWKS Endpoint for TypeScript

---

lambdas/src/common/security/jwt-verifier.ts
lambdas/src/handlers/access-token-handler.ts
lambdas/src/middlewares/error/error-middleware.ts
lambdas/tests/unit/handlers/access-token-handler.test.ts
lambdas/tests/unit/handlers/session-handler.test.ts

Added `jwt_verification_failed` metric to TS session and token
Note: There seems to be an issue with metrics not being published when errors are thrown by the `validateJwtMiddleware` and caught by the `errorMiddleware`. I have added `metrics.publishStoredMetrics();` in the errorMiddleware to make sure the new metric is published. This can/should be looked at in more detail if needed in the future.
Now that we are consuming Cores public signing keys from an endpoint rather than SSM there is more risk that something will go wrong when verifying requests from Core
- [OJ-3080](https://govukverify.atlassian.net/browse/OJ-3080)
[OJ-3080]: https://govukverify.atlassian.net/browse/OJ-3080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3080: Add jwt_verification_failed metric to TS session and token

---

test-resources/infrastructure/template.yaml

Set DequeueEvents to false when the environment is staging/integration as we do not want events being dequeued in those environments.
Added integration to the AllowedValues for Environment parameter to match this. 
- [OJ-3171](https://govukverify.atlassian.net/browse/OJ-3171)
[OJ-3171]: https://govukverify.atlassian.net/browse/OJ-3171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: do not dequeue events in staging & integration

---

infrastructure/lambda/template.yaml

Move Session and Token lambdas that use the devplatform VPC to the protected subnet.
The session and token lambdas need to fetch Core’s public signing key from their jwks endpoint
- [OJ-3181](https://govukverify.atlassian.net/browse/OJ-3181)
[OJ-3181]: https://govukverify.atlassian.net/browse/OJ-3181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3181: Move Session and Token lambdas on devplatform VPC to protected

---

test-resources/headless-core-stub/lambdas/callback/src/callback-handler.ts
test-resources/headless-core-stub/lambdas/mock-jwks/src/mock-jwk-handler.ts
test-resources/headless-core-stub/lambdas/start/src/services/signing-service.ts
test-resources/headless-core-stub/lambdas/start/src/start-handler.ts
test-resources/headless-core-stub/lambdas/start/tests/services/signing-service.test.ts
test-resources/headless-core-stub/utils/src/audience-formatter/index.ts
test-resources/headless-core-stub/utils/src/jwks-cache-control/index.ts
test-resources/headless-core-stub/utils/tests/audience-formatter/index.test.ts
test-resources/headless-core-stub/utils/tests/jwks-cache-control/index.test.ts
test-resources/infrastructure/template.yaml

Added functionality to call the hosted .well-known/jwks.json of the CRI.
The headless core stub using the jwk to encrypt the JAR
The Key-rotation step function has been run and a bootstrap key is available for use, which can be used to encrypt the payload by the headless core stub. The CRI should be able to decrypt this request when it comes throught the session handler
A valid ./well-known/jwks.json exist at https://api.review-a.dev.account.gov.uk/.well-known/jwks.json
- [OJ-3158](https://govukverify.atlassian.net/browse/OJ-3158)
[OJ-3158]: https://govukverify.atlassian.net/browse/OJ-3158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3158: use cri published keys

---

infrastructure/lambda/template.yaml

Removed `PUBLIC_JWKS_ENDPOINT` from Session and Token env variables.
Added jwksEndpoint SSM params for multiple client ids.
To support multiple client ids that may use different public JWKS endpoints, this moves the endpoint URL into SSM params per client.
- [OJ-3174](https://govukverify.atlassian.net/browse/OJ-3174)
[OJ-3174]: https://govukverify.atlassian.net/browse/OJ-3174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3174: Move JWKS Endpoint from ENV variable to SSM Params

---

build.gradle

Bumped cri-lib -> 6.1.0 to include JWKS endpoint being retrieved from SSM to support multiple clients.
The CRIs need to consume the public signing key from the service that signed the JWT.
- [OJ-3175](https://govukverify.atlassian.net/browse/OJ-3175)
[OJ-3175]: https://govukverify.atlassian.net/browse/OJ-3175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3175: Bump cri-lib to include ssm jwks endpoints

---

infrastructure/lambda/template.yaml

Rename from KeyRotationEnabled to `CorePublicSigningJwksEnabled`
We have KeyRotationEnabled and KeyRotationMapping, they look very similar but are very different
To prevent me from getting confused, I have had to look at both and find out which is which and does what

Chore: Rename core jwks mapping

---

infrastructure/lambda/template.yaml

Enable `CorePublicSigningJwksEnabled` for check-hmrc for dev, build & staging
A One Login user must be able to continue their identity proving journey whilst a key rotation is taking place in IPV Core.
- [OJ-3078](https://govukverify.atlassian.net/browse/OJ-3078)
[OJ-3078]: https://govukverify.atlassian.net/browse/OJ-3078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3078: Enable CorePublicSigningJwksEnabled for check-hmrc upto staging

---

infrastructure/lambda/template.yaml

Switched on consumption of the core JWKS endpoint in KBV integration + production.
We want to ensure an unbroken user journey while signing keys are rotated.
OJ-3173

OJ-3173 - Set CorePublicSigningJwksEnabled=true for KBV prod+int

---

infrastructure/lambda/template.yaml

ENV_VAR_FEATURE_CONSUME_PUBLIC_JWK feature flag switched on in dev so that the Core stub can be deployed and tested. feature flag will need to be turned back off in Dev once the change is pushed to higher envs to re-enable other local Dev testing.
- [LIME-1660](https://govukverify.atlassian.net/browse/LIME-1660)
[LIME-1660]: https://govukverify.atlassian.net/browse/LIME-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1660 feature flag enabled to test Core/Stub JWKS endpoint in passport dev

---

infrastructure/lambda/template.yaml
lambdas/src/services/security/jwe-decrypter.ts
lambdas/tests/unit/services/security/jwe-decrypter.test.ts
test-resources/integration-tests/helpers/jwe-decrypter.ts

Given KeyRotation is enabled using `ENV_VAR_FEATURE_FLAG_KEY_ROTATION`
for Experian KBV (dev/build) it is expected to start using kms key alias of the rotated key to try to decrypt payload that has been encrypted using public encryption key of the alias key
`ENV_VAR_FEATURE_FLAG_KEY_ROTATION_LEGACY_KEY_FALLBACK` has been added to maintain parity with the [java decrypter ](https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/487) below is the observed behaviours
Decrypter tries to decrypt payload using legacy route and fails as expected
Decrypter tries to decrypt payload using key rotation active alias and succeeds as expected
Decrypter tries to decrypt payload using legacy route and succeeds as expected
Decrypter tries to decrypt payload using all known key rotation aliases and …

OJ-3185: Allow decrypting with KMS alias of key-rotation keys

---

test-resources/infrastructure/template.yaml

Enable Key rotation for up to build environment for headless core stub so requests made by the start handler in those environments use encryption key from  `./well-known/jwks.json` to make JAR request
We've enabled Key rotation for Experian KBV up to build we also need to enabled key rotation for request made by the start handler in those environments
Part of effectively managing keys i.e. to enable easier rotation of keys used by CRI clients such as core to make requests to CRI
- [OJ-3185:(https://govukverify.atlassian.net/browse/OJ-3185)

OJ-3185: Enable key rotation headless for Experian KBV

---

infrastructure/lambda/template.yaml

- Fix Evaluation periods in canary 5xx error alarms
- Fix Evaluation periods in canary 5xx error alarms
- In order to canary to cause a rollback in the instance of an error, the 5xx error alarm should be configured with right thresholds.
- [IPS-1894](https://govukverify.atlassian.net/browse/IPS-1894)
[IPS-1894]: https://govukverify.atlassian.net/browse/IPS-1894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-1894: Fix Evaluation periods in canary 5xx error alarms

---

infrastructure/lambda/template.yaml

Setting ENV_VAR_FEATURE_CONSUME_PUBLIC_JWK to true.
Testing the Core-Stub JWKS Endpoint in dev.
- [LIME-1729](https://govukverify.atlassian.net/browse/LIME-1729)
[LIME-1729]: https://govukverify.atlassian.net/browse/LIME-1729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1729: Turning on feature flag for ENV_VAR_FEATURE_CONSUME_PUBLIC_JWK for fraud dev

---

lambdas/package.json
package-lock.json

Bump pact and wait-on, add form-data overrides
form-data vulnerability was fixed in axios 1.11.0 but pact and wait-on are still using old versions of axios.
Bumped to the latest version so that we're ready to upgrade when we can, added a forced override to use form-data 4.0.4 which is the patched version
https://github.com/axios/axios/pull/6970
- [OJ-3271](https://govukverify.atlassian.net/browse/OJ-3271)
[OJ-3271]: https://govukverify.atlassian.net/browse/OJ-3271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3271: Bump pact and wait-on, add form-data overrides

---

lambdas/src/common/security/jwt-verifier.ts
lambdas/src/middlewares/error/error-middleware.ts
lambdas/src/services/session-request-validator.ts
lambdas/tests/unit/common/security/jwt-verifier.test.ts
lambdas/tests/unit/handlers/session-handler.test.ts
lambdas/tests/unit/services/session-request-validator.test.ts

Split expired JWT's out from the `jwt_verification_failed` into it's own `jwt_expired` metric.
This required some changes to throw the actual error rather than returning null.
We want to see how easily see how many expired JWTs are sent to our CRI, and we do not want these included in the `jwt_verification_failed`
- [OJ-3249](https://govukverify.atlassian.net/browse/OJ-3249)
Expired JWT sent first, than a none expired JWT but with another issue
[OJ-3249]: https://govukverify.atlassian.net/browse/OJ-3249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3249: Add new jwt_expired metric

---

infrastructure/lambda/template.yaml

Passport CRI - Enable KeyRotationLegacyFallback and KeyRotation in Production
Passport CRI - Disable KeyRotationLegacyFallback in Integration
To enable key-rotations in Production
To remove the legacy fallback in Integration now the rotation has taken place.
- [LIME-1727](https://govukverify.atlassian.net/browse/LIME-1727)
[LIME-1727]: https://govukverify.atlassian.net/browse/LIME-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1727 Passport CRI (Production) - Enable KeyRotationLegacyFallBackMapping and KeyRotationMapping

---

infrastructure/lambda/template.yaml

Returned FallbackKey to "false" for fraud and dl dev as we have now migrated to the automated key-rotation process for fraud and dl dev
- [LIME-1733](https://govukverify.atlassian.net/browse/LIME-1733)
- [LIME-1738](https://govukverify.atlassian.net/browse/LIME-1738)
[LIME-1733]: https://govukverify.atlassian.net/browse/LIME-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1738]: https://govukverify.atlassian.net/browse/LIME-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1733-1738 return legacyFallbackKey flag to false in fraud and dl dev

---

infrastructure/lambda/template.yaml

ENV_VAR_FEATURE_FLAG_KEY_ROTATION and KeyRotationLegacyFallBack switched to 'true' for Fraud Build to allow for migration and key rotation in Fraud Build.
- [LIME-1823](https://govukverify.atlassian.net/browse/LIME-1823)
[LIME-1823]: https://govukverify.atlassian.net/browse/LIME-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1823: KeyRotation and LegacyKey set to 'true' for Fraud Build.

---

infrastructure/lambda/template.yaml

- Enabled Lambda provisioned concurrency (=1) on common lambdas in NINo Check build + prod
- The NINo check flow is not used regularly enough to consistently have at least one warm Lambda, meaning we often see cold starts that affect user experience and compromise our adherence to NFRs
- OJ-3348

OJ-3348 - Enable provisioned concurrency in check build+prod

---

infrastructure/lambda/template.yaml

Returned KeyRotationLegacyFallBackMapping to "false" for Driving License Build as we have now migrated to the automated key-rotation process for Driving License Build.
- [LIME-1824](https://govukverify.atlassian.net/browse/LIME-1824)
[LIME-1824]: https://govukverify.atlassian.net/browse/LIME-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1824: Return LegacyFallbackKey flag to false in DL Build.

---

infrastructure/lambda/template.yaml

Enable the feature flags `ENV_VAR_FEATURE_FLAG_KEY_ROTATION` and `ENV_VAR_FEATURE_FLAG_KEY_ROTATION_LEGACY_KEY_FALLBACK` for check HMRC CRI in staging
Because we are doing a key rotation in staging tomorrow
- [OJ-3254](https://govukverify.atlassian.net/browse/OJ-3254)
[OJ-3254]: https://govukverify.atlassian.net/browse/OJ-3254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3254: Enable key rotation env vars

---

test-resources/infrastructure/template.yaml

Turn on `KEY_ROTATION_FEATURE_FLAG_ENABLED` 
So that the headless core stub uses the public encryption keys from the jwks endpoint to encrypt the JWTs that it produces
- [OJ-3255](https://govukverify.atlassian.net/browse/OJ-3255)
[OJ-3254]: https://govukverify.atlassian.net/browse/OJ-3254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-3255]: https://govukverify.atlassian.net/browse/OJ-3255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3255: turn on key rotation in stub

---

infrastructure/lambda/template.yaml

Fraud CRI (Staging) disable KeyRotationLegacyFallBackMapping
Fraud Staging is now using alias based rotated keys
- [LIME-1816](https://govukverify.atlassian.net/browse/LIME-1816)
[LIME-1816]: https://govukverify.atlassian.net/browse/LIME-1816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1816 Fraud CRI (Staging) - disable KeyRotationLegacyFallBackMapping

---

infrastructure/lambda/template.yaml

Fraud CRI (Integration) disable KeyRotationLegacyFallBackMapping
Fraud Int is now using alias based rotated keys
- [LIME-1817](https://govukverify.atlassian.net/browse/LIME-1817)
[LIME-1817]: https://govukverify.atlassian.net/browse/LIME-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1817 Fraud Int disable fallback mapping

---

infrastructure/lambda/template.yaml

Fraud CRI (Prod) disable KeyRotationLegacyFallBackMapping
Fraud Prod is now using alias based rotated keys
- [LIME-1818](https://govukverify.atlassian.net/browse/LIME-1818)
[LIME-1818]: https://govukverify.atlassian.net/browse/LIME-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fraud CRI (prod) - disable KeyRotationLegacyFallBackMapping

---

test-resources/infrastructure/template.yaml

Turn on `KEY_ROTATION_FEATURE_FLAG_ENABLED`
So that the headless core stub uses the public encryption keys from the jwks endpoint to encrypt the JWTs that it produces
- [OJ-3256](https://govukverify.atlassian.net/browse/OJ-3256)
[OJ-3256]: https://govukverify.atlassian.net/browse/OJ-3256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3256: feat - turn on key rotation for staging in stubs

---

infrastructure/lambda/template.yaml

Enable the feature flags `ENV_VAR_FEATURE_FLAG_KEY_ROTATION` and the `ENV_VAR_FEATURE_FLAG_KEY_ROTATION_LEGACY_KEY_FALLBACK` for KBV CRI in Staging.
To enable key rotation in Staging
- [OJ-3256](https://govukverify.atlassian.net/browse/OJ-3256)
[OJ-3256]: https://govukverify.atlassian.net/browse/OJ-3256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3256: feat - enable key rotation env variables in staging

---

infrastructure/lambda/template.yaml

Dynatrace OneAgent Layer first needs to resolve to v1_311 before then updating the version to v1_313.
There’s a bug in the {{resolve:secretsmanager}} syntax that prevents the current configuration from deploying the latest available Dynatrace layer.
- [LIME-1843](https://govukverify.atlassian.net/browse/LIME-1843)
[LIME-1843]: https://govukverify.atlassian.net/browse/LIME-1843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1843 Update dynatrace layer version for node and java functions

---

test-resources/infrastructure/template.yaml

Turn on key rotation for KBV
So that journeys starting from the stub use public encryption keys from our jwks endpoint.
- [OJ-3257](https://govukverify.atlassian.net/browse/OJ-3257)
[OJ-3257]: https://govukverify.atlassian.net/browse/OJ-3257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3257: Turn on key rotation for KBV

---

test-resources/infrastructure/template.yaml

We've enabled key rotation flags in Address staging
https://github.com/govuk-one-login/ipv-cri-common-lambdas/pull/571
Enabling key rotation in Address staging
- [OJ-3232](https://govukverify.atlassian.net/browse/OJ-3232)
[OJ-3232]: https://govukverify.atlassian.net/browse/OJ-3232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3232: Turn on key rotation for address in Staging

---

infrastructure/lambda/template.yaml

DL CRI (Integration) disable KeyRotationLegacyFallBackMapping
DL Integration is now using alias based rotated keys
- [LIME-1820](https://govukverify.atlassian.net/browse/LIME-1820)
[LIME-1820]: https://govukverify.atlassian.net/browse/LIME-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1820 DL CRI (Integration) - disable key rotation fallback mapping

---

infrastructure/lambda/template.yaml

- Enabled key rotation in address int+prod common lambdas
- We are running the first key rotations for address later this week
- OJ-3251

OJ-3251 - Enable key rotation feature flag in address int+prod

---

infrastructure/lambda/template.yaml

Turn off snapstart for Address
Java lambdas are not being used in prod but they are being effected by the DT issue
- [OJ-3437](https://govukverify.atlassian.net/browse/OJ-3437)
[OJ-3437]: https://govukverify.atlassian.net/browse/OJ-3437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3437: Turn off snapstart for Address

---

infrastructure/lambda/template.yaml
test-resources/infrastructure/template.yaml

Apply tagging conditional to our regional API GW resources that support testing. Tags added to;
- Common lambdas pre merge API
- Test resources API
Note: `AWS::ApiGateway::RestApi` requires tags to be an array of key-value pairs
As part of transitioning FMS WAF rule enforcement from COUNT to BLOCK, Security have set up custom policies for us to apply to our resources in scope. In COUNT mode FMS merely logs the rule violations, in BLOCK mode violating requests are actively blocked.
- [OJ-3457](https://govukverify.atlassian.net/browse/OJ-3457)
[OJ-3457]: https://govukverify.atlassian.net/browse/OJ-3457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OJ-3457: Add FMS tags to pre-merge APIGW and test-resources APIGW
