- accesstoken/src/main/java/uk/gov/di/ipv/cri/address/api/handler/AccessTokenHandler.java
- accesstoken/src/test/java/uk/gov/di/ipv/cri/address/api/handler/AccessTokenHandlerTest.java
- jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetHandler.java
- jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetService.java
- jwkset/src/main/java/uk/gov/di/ipv/cri/address/api/handler/KMSService.java
- jwkset/src/test/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetHandlerTest.java
- jwkset/src/test/java/uk/gov/di/ipv/cri/address/api/handler/JWKSetServiceTest.java
- jwkset/src/test/java/uk/gov/di/ipv/cri/address/api/handler/KMSServiceTest.java
- session/src/main/java/uk/gov/di/ipv/cri/address/api/handler/SessionHandler.java
- session/src/main/java/uk/gov/di/ipv/cri/address/api/service/KMSRSADecrypter.java
- session/src/test/java/uk/gov/di/ipv/cri/address/api/handler/SessionHandlerTest.java
- session/src/test/java/uk/gov/di/ipv/cri/address/api/service/KMSRSADecrypterTest.java
Refactored CanonicalAddress to use LocalDate rather than Date to support nulls without the need for Optional
> Refactor to use the AWS SDK v2, rather than v1

- session/src/main/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestService.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestServiceTest.java
Update imports to refer to the new package for the SharedClaims class
Related to:
- [KBV-106](https://govukverify.atlassian.net/browse/KBV-106)
> BAU - refactor domain person identity package

- session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java
- Session lambda function updated to send user-specific audit data
( a future improvement could be to return the `SessionItem` from the `sessionService.saveSession(sessionRequest)` method )
As requested by the TxMA team.
- [KBV-622](https://govukverify.atlassian.net/browse/KBV-622)
> KBV-622 - Add user data to session start audit event

- .github/workflows/post-merge-deploy-to-poc.yml
List the sam build directory contents
To identify where the build artefact exists
> List sam build dir contents (temporarily)

- infrastructure/lambda/template.yaml
- Corrected the session lambda function code uri
- It was incorrect
> OJ-892 - correct the session lambda function code uri

- infrastructure/lambda/template.yaml
- `template.yaml` updated to work with the latest `common-cri-parameters`
> OJ-892 deploy common lambdas to poc

- infrastructure/lambda/template.yaml
New log subscription filter to send logs to an additional CSLS endpoint
> feat: new log subscription filter to send logs to new CSLS endpoint

- .github/workflows/post-merge-matrix-deploy.yml
- .gitignore
- accesstoken/build.gradle
- authorization/build.gradle
- build.gradle
- deploy.sh
- infrastructure/lambda/template.yaml
- session/build.gradle
- settings.gradle
* Build common lambdas with AWS SAM cli tool instead of using gradle directly to build a zip
* Use `deploy.sh` to deploy to our dev environment
* Remove dependency on each dev maintaining a `samconfig.toml` file
* Remove unneeded dependency declarations like `soap` and `hibernate`
This has been tested with a deploy to the cri dev environment and a test of the session lambda.
> Build common-lambdas with sam

- .github/workflows/post-merge-matrix-deploy.yml
- .gitignore
- accesstoken/build.gradle
- authorization/build.gradle
- build.gradle
- deploy.sh
- infrastructure/lambda/template.yaml
- session/build.gradle
- session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
- settings.gradle
Reverts alphagov/di-ipv-cri-common-lambdas#48
> Build common-lambdas with sam take 2

- infrastructure/lambda/template.yaml
- Removed unnecessary log group subscription filters
- At the request of @instantiator 
- [OJ-1015](https://govukverify.atlassian.net/browse/OJ-1015)
> OJ-1015 - Remove unnecessary log group subscription filters

- session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java
Changed "x-forwarded-for" header  to "X-Forwarded-For".
Changed "x-forwarded-for" header  to "X-Forwarded-For".
Fixing the header.
- [OJ-923](https://govukverify.atlassian.net/browse/OJ-923)
> OJ-923: Correct X-Forwarded-For Header

- .github/dependabot.yml
> OJ-1050-add-dependabot

- .secrets.baseline
- infrastructure/lambda/template.yaml
Add CIC on template to run secure pipeline
Added CIC on template
changed it so secure pipeline can run
https://govukverify.atlassian.net/browse/F2F-143
> F2F-143 added cic for mapping

- .github/workflows/post-merge-matrix-deploy.yml
- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge-checks.yml
- .github/workflows/pre-merge-integration-test.yml
- .secrets.baseline
Workflows have been updated:
* Deprecated GHA actions have been updated to the newer versions.
* setup-sam fix has been applied
Primarily to apply the setup-sam fix so that the workflows are not broken.
(https://github.com/aws/aws-sam-cli/issues/4527)
Secondly in preparation for GitHub to remove the deprecated functionality.
- [OJ-1146](https://govukverify.atlassian.net/browse/OJ-1146)
[OJ-1146]: https://govukverify.atlassian.net/browse/OJ-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1146 workflow deprecations and sam fix

- .github/workflows/post-merge-matrix-deploy.yml
- .github/workflows/pre-merge-integration-test.yml
- .secrets.baseline
- accesstoken2/package-lock.json
- accesstoken2/package.json
- accesstoken2/src/app.ts
- infrastructure/lambda/template.yaml
Add basic lambda function to service
Setting up for a new lambda
> BAU-setup-accesstoken-2-base-lambda

- accesstoken2/jest.config.ts
- accesstoken2/src/app.ts
- accesstoken2/src/services/session-service.ts
- accesstoken2/src/services/token-request-validator.ts
- accesstoken2/src/types/errors.ts
- accesstoken2/tests/unit/app.test.ts
> Access token git/update error handling

- accesstoken2/src/app.ts
- accesstoken2/src/models/request_payload.ts
- accesstoken2/src/services/token-request-validator.ts
- accesstoken2/src/types/errors.ts
- accesstoken2/src/types/request_payload.ts
Moved conditionals from main handler into Accesstokenvalidator.
Introduce type for token request
Refactored
> Refactor accesstokenvalidator

- .gitignore
- README.md
- integration-tests/build.gradle
- integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/runners/RunCucumberTest.java
- integration-tests/src/test/resources/allure.properties
We have added Allure reporting to this repo
We did not have Allure previously
OJ-1173
https://govukverify.atlassian.net/jira/software/c/projects/OJ/boards/166?modal=detail&selectedIssue=OJ-1173&assignee=617fdbaaf485cd00680cb8be&assignee=60bdd0d58f2cc10069551099
> Oj 1173 allure for common lambdas

- lambdas/src/handlers/session-handler.ts
- lambdas/src/services/person-identity-service.ts
- lambdas/src/session-service.ts
This should have been a revert, I didn't want to have to relink the imports so this is a separate PR
These work with acceptance test locally. So it's a good state
> BAU: Inject config service for session and person Identity service

- infrastructure/lambda/template.yaml
> remove use of lambda layers on typescript functions

- lambdas/tests/unit/common/utils/request-utils.test.ts
> BAU: Added test for request utils

- lambdas/jest.config.ts
- lambdas/setEnvVars.js
- lambdas/src/common/config/config-service.ts
- lambdas/tests/unit/common/config/config-service.test.ts
Config service unit tests
- [OJ-1202](https://govukverify.atlassian.net/browse/OJ-1202)
[OJ-1202]: https://govukverify.atlassian.net/browse/OJ-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1202 add config service unit tests

- lambdas/src/common/security/jwt-verifier.ts
- lambdas/tests/unit/services/jwt-verifier.test.ts
Added test coverage for jwt-verifier
> BAU: Added test for jwtverifier

- lambdas/src/handlers/authorization-handler.ts
- lambdas/tests/unit/handlers/authorization-handler.test.ts
Fixed commented out and failing unit tests for the session-service. Removed redundant and unused code.
- [OJ-1200](https://govukverify.atlassian.net/browse/OJ-1200)
[OJ-1200]: https://govukverify.atlassian.net/browse/OJ-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1200: Authorization Handler Unit Test

- lambdas/src/handlers/session-handler.ts
- lambdas/tests/unit/handlers/session-handler.test.ts
Added unit tests for the session handler
Improve unit test coverage
- [OJ-1199](https://govukverify.atlassian.net/browse/OJ-1199)
[OJ-1199]: https://govukverify.atlassian.net/browse/OJ-1199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1199 session handler unit tests

- lambdas/tests/unit/services/session-service.test.ts
Fixed commented out and failing unit tests for the session-service. Removed redundant and unused code.
- [OJ-1198](https://govukverify.atlassian.net/browse/OJ-1198)
[OJ-1198]: https://govukverify.atlassian.net/browse/OJ-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OG-1198: Session Service Unit Test

- lambdas/src/services/session-request-validator.ts
- lambdas/tests/unit/common/config/config-service.test.ts
- lambdas/tests/unit/common/services/audit-service.test.ts
- lambdas/tests/unit/services/person-identity-service.test.ts
- lambdas/tests/unit/services/session-request-validator.test.ts
Session request validator unit tests (prettier has been run)
Improve test coverage for existing unit test files
Improve unit test coverage
- [OJ-1225](https://govukverify.atlassian.net/browse/OJ-1225)
[OJ-1225]: https://govukverify.atlassian.net/browse/OJ-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1225 session request validator unit tests

- lambdas/jest.config.ts
Add code coverage for all files, not just files that have tests.
> Apply code coverage to all code

- lambdas/tests/unit/handlers/access-token-handler.test.ts
Fixed commented out and failing unit tests for the session-service. Removed redundant and unused code.
- [OJ-1197](https://govukverify.atlassian.net/browse/OJ-1197)
[OJ-1197]: https://govukverify.atlassian.net/browse/OJ-1197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OG-1197: Access Token Handler Unit Test

- README.md
- integration-tests/build.gradle
- integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/runners/RunCucumberTest.java
- integration-tests/src/test/resources/allure.properties
> chore: Remove Allure reporting

- lambdas/tests/unit/handlers/access-token-handler.test.ts
Types were renamed while this PR was in flight.
> tests: Fix broken type import

- lambdas/src/common/aws-client-factory.ts
- lambdas/src/common/security/jwt-verifier.ts
- lambdas/src/common/services/audit-service.ts
- lambdas/src/handlers/access-token-handler.ts
- lambdas/src/handlers/authorization-handler.ts
- lambdas/src/handlers/session-handler.ts
- lambdas/src/services/person-identity-service.ts
- lambdas/src/services/session-service.ts
- lambdas/src/services/token-request-validator.ts
- lambdas/src/types/bearer-access-token.ts
- lambdas/src/types/request_payload.ts
- lambdas/src/types/session-item.ts
- lambdas/tests/unit/common/config/config-service.test.ts
- lambdas/tests/unit/common/services/audit-service.test.ts
- lambdas/tests/unit/common/utils/request-utils.test.ts
- lambdas/tests/unit/services/jwt-verifier.test.ts
- lambdas/tests/unit/services/person-identity-service.test.ts
- lambdas/tests/unit/services/security/jwe-decrypter.test.ts
Applied Prettier autoformat across the `src` and `tests` directory. This isn't currently being enforced so these files slipped thorugh.
#117 adds a GHA to apply this check on all future PRs
> chore: Apply prettier

- lambdas/setEnvVars.js
- lambdas/src/services/auth-request-validator.ts
- lambdas/tests/unit/services/auth-request-validator.test.ts
- lambdas/tests/unit/services/session-service.test.ts
Improve session service test coverage
run prettier
Test coverage
> Chore/coverage Improve unit test coverage

- .github/workflows/pre-merge-integration-test.yml
> fix: Pin gradle to ./gradlew

- lambdas/sonar-project.properties
Add explicit `src` and `tests` directories to sonarcloud config
> Add src/test properties to sonarcloud config

- lambdas/src/handlers/access-token-handler.ts
- lambdas/tests/unit/handlers/access-token-handler.test.ts
Add metrics handler to the access token handler lambda
- [OJ-1216](https://govukverify.atlassian.net/browse/OJ-1216)
[OJ-1216]: https://govukverify.atlassian.net/browse/OJ-1216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1216 add metrics to access token handler

- lambdas/src/types/errors.ts
- lambdas/tests/unit/handlers/authorization-handler.test.ts
- lambdas/tests/unit/services/auth-request-validator.test.ts
Integration test fails, caught unintended drift from java code see 
The issue was caused by the SessionValidationError overriding the `getErrorSummary` the fix was to remove this.
Unintended enhancement
- [OJ-1174](https://govukverify.atlassian.net/browse/OJ-1174)
[OJ-1174]: https://govukverify.atlassian.net/browse/OJ-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1174: This a fix for issue caught by integration test

- integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
- integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/util/IpvCoreStubUtil.java
- integration-tests/src/test/resources/features/AccessTokenAPI.feature
- integration-tests/src/test/resources/features/AuthorizationAPI.feature
- integration-tests/src/test/resources/features/SessionAPI.feature
Acceptance Test coverage for TS lambda
To increase the coverage for both JAVA and TS lamda
> TS lambda test coverage

- lambdas/src/services/person-identity-service.ts
- lambdas/tests/unit/common/services/audit-service.test.ts
Applied auto fix provided by running eslint, 
Removed unecessary if conditions in person-identity-service.ts
The methods are return and empty array by default since the signature requires an array
Linting throws some warning which can be address this a small change toward addressing them
Code improvement
- [OJ-1270](https://govukverify.atlassian.net/browse/OJ-1270)
> OJ-1270: apply eslint auto fix and minor refactoring

- lambdas/src/common/security/jwt-verifier.ts
- lambdas/tests/unit/common/config/config-service.test.ts
- lambdas/tests/unit/common/services/audit-service.test.ts
ESlint is reporting error and warning, this PR fixes the errors only, leaving warnings for future PR'S
Fix eslint errors
eslint identified errors and warnings this fixes the errors
- [OJ-1270](https://govukverify.atlassian.net/browse/OJ-1270)
> OJ-1270: Fix eslint errors only

- lambdas/src/services/session-service.ts
- lambdas/src/types/errors.ts
- lambdas/tests/unit/handlers/access-token-handler.test.ts
session-service.ts
errors.ts
access-token-handler.test.ts
session-service does not check if access or auth codes have expired like in the Java versions. This PR adds that and unit tests. 
- [OJ-1257](https://govukverify.atlassian.net/browse/OJ-1257)
[OJ-1257]: https://govukverify.atlassian.net/browse/OJ-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Oj 1257 access token handler coverage new branch on main

- lambdas/jest.config.ts
Add code coverage based upon current achieved levels.
Above 90% is a good level to aim for, but we're almost hitting 100% everywhere.
I've called out `security` as needing specific levels - as we improve the coverage, we can bump them up, and once everything is at 100%, we can remove those sections.
> chore: Add code coverage thresholds

- lambdas/src/handlers/access-token-handler.ts
- lambdas/src/handlers/authorization-handler.ts
- lambdas/src/handlers/session-handler.ts
- lambdas/src/types/errors.ts
This is the 2nd part of fixing eslinting errors, in this case no-implicit-any warnings are addressed
A separate PR would looking into fix the use of any in the catch block of the lambda handler
which is not as straight for as the fixes here
Fix eslint warnings
Code improvements recommended by eslint rules
- [OJ-1270](https://govukverify.atlassian.net/browse/1270])
> OJ-1270: fix eslint no implicit any part-2

- lambdas/src/common/config/config-service.ts
- lambdas/src/common/services/audit-service.ts
- lambdas/src/handlers/access-token-handler.ts
- lambdas/src/services/token-request-validator.ts
- lambdas/tests/unit/common/config/config-service.test.ts
Code improvement to make ESlint happier
- [OJ-1270](https://govukverify.atlassian.net/browse/OJ-1270)
> OJ-1270: Fix eslint warning forbidden non null assertion warnings

- .github/workflows/post-merge-matrix-deploy.yml
Yaml indentation was incorrect
To fix the workflow
- [OJ-1247](https://govukverify.atlassian.net/browse/OJ-1247)
[OJ-1247]: https://govukverify.atlassian.net/browse/OJ-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: yaml indentation

- .github/workflows/post-merge-matrix-deploy.yml
- .secrets.baseline
Remove incorrect always conditional
It breaks the workflow
- [OJ-1247](https://govukverify.atlassian.net/browse/OJ-1247)
[OJ-1247]: https://govukverify.atlassian.net/browse/OJ-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove erroneous always condition

- .github/workflows/post-merge-matrix-deploy.yml
- .secrets.baseline
Revert always change and correct indentation
Removing always was a mistake, actual issue was level of concurrency indentation
- [OJ-1247](https://govukverify.atlassian.net/browse/OJ-1247)
[OJ-1247]: https://govukverify.atlassian.net/browse/OJ-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: concurrency indentation and always

- .github/workflows/post-merge-matrix-deploy.yml
- .github/workflows/pre-commit.yml
- .github/workflows/pre-merge-integration-test.yml
- .secrets.baseline
Pinned versions of:
- Python
- SAM
- Prevent issues with auto updates from SAM
- [OJ-1275](https://govukverify.atlassian.net/browse/OJ-1275)
[OJ-1275]: https://govukverify.atlassian.net/browse/OJ-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OJ-1275] Pin software versions in all repos

- lambdas/package-lock.json
- lambdas/package.json
`package.json` properties have some standards.
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#name
This PR fixes two issues:
- New packages must not have uppercase letters in the name.
- The name ends up being part of a URL, an argument on the command line, and a folder name. Therefore, the name can't contain any non-URL-safe characters.
> fix: Ensure package name matches standards

- infrastructure/lambda/template.yaml
Added a subscription filter for the new Typescript lambdas that already exists with the java lamdbas
HOPEFULLY to allow for the TS lambdas to log to splunk
> Add logging subscription filter for Splunk

- lambdas/src/services/session-service.ts
- lambdas/src/types/errors.ts
- lambdas/src/types/session-item.ts
- lambdas/tests/unit/handlers/access-token-handler.test.ts
- lambdas/tests/unit/handlers/authorization-handler.test.ts
- lambdas/tests/unit/services/session-service.test.ts
- lambdas/tests/unit/services/token-request-validator.test.ts
session-item updated to include expiryDate. 
session-service updated to check if the expiryDate is valid and if not throw exception
unit tests updated to accommodate the new field added to session-item.
To match what is in the Java implementation.
- [OJ-1265](https://govukverify.atlassian.net/browse/OJ-1265)
[OJ-1265]: https://govukverify.atlassian.net/browse/OJ-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Oj 1265 session expiry

- lambdas/src/services/session-request-validator.ts
- lambdas/tests/unit/services/session-request-validator.test.ts
> Hotfix: Comment out scope checks

- .secrets.baseline
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestServiceTest.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SignedJWTBuilder.java
see: https://github.com/alphagov/di-ipv-cri-common-lambdas/pull/173
Cleanup the above, by reusing existing code
Also addressed code smell in the above
> BAU: cleanup current fix:

- infrastructure/lambda/pre-merge-api.yaml
- infrastructure/lambda/template.yaml
- integration-tests/src/test/java/gov/uk/di/ipv/cri/common/api/stepDefinitions/APISteps.java
Renaming the lambdas from "Two" to "TS" for clarity
Provide more clarity for us and other teams
Better practice
> Rename new lambdas from two to TS

- .github/workflows/pre-merge-integration-test.yml
Use configure-aws-credentials@v2 which came out last week
> Use configure-aws-credentials@v2

- .secrets.baseline
- build.gradle
- session/src/main/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestService.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestServiceTest.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SignedJWTBuilder.java
This PR uses the Redaction Deserializer see https://github.com/alphagov/di-ipv-cri-lib/pull/201
> OJ-1305: Use the redaction deserializer

- lambdas/package-lock.json
- lambdas/package.json
Still not found the issue yet, lets upgrade and see if there is a difference
- [OJ-1413](https://govukverify.atlassian.net/browse/OJ-1413)
[OJ-1413]: https://govukverify.atlassian.net/browse/OJ-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1413: upgrade aws lambda powertools:

- .secrets.baseline
- infrastructure/lambda/template.yaml
Consolidate duplicated audience mappings into a a single map
The template was overly messy and confusing
> BAU consolidate cri audiance mappings

- .secrets.baseline
- infrastructure/lambda/template.yaml
Added configuration for new AWS stub
Additional configuration
Moving from PAAS stub to AWS stub
> OJ-1439: Added AWS stub config

- .gitignore
> BAU add bins to gitignore

- .secrets.baseline
- infrastructure/lambda/template.yaml
Add new config entries for AWS Pre-prod mean't to be replacing PAAS variant
Moving from PAAS to AWS 
See above
> OJ-1439: Add config elements for pre-prod aws build

- .secrets.baseline
- infrastructure/lambda/template.yaml
Added configuration for new AWS stub prod
Additional configuration
Moving from PAAS stub to AWS stub
- [OJ-1439](https://govukverify.atlassian.net/browse/OJ-1439)
[OJ-1439]: https://govukverify.atlassian.net/browse/OJ-1439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1439: config for stub aws prod

- .github/workflows/pre-merge-integration-test.yml
- integration-tests/src/test/resources/cucumber.properties
> added code for cucumber reporting

- .secrets.baseline
- deploy.sh
- infrastructure/lambda/template.yaml
Add the necessary mappings for the toy api
Needed to spin up the di-ipv-cri-toy-api stack
- [OJ-1396](https://govukverify.atlassian.net/browse/OJ-1396)
[OJ-1396]: https://govukverify.atlassian.net/browse/OJ-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1396 updates for toy api

- .github/workflows/post-merge-matrix-deploy.yml
- .secrets.baseline
Reverts alphagov/di-ipv-cri-common-lambdas#210
> Revert "oj-1516 toy deployments plus dev-platform upload action"

- .github/workflows/post-merge-matrix-deploy-toy.yml
- .secrets.baseline
- infrastructure/lambda/template.yaml
Added new workflow using the [di-dev-platform-upload-action](https://github.com/alphagov/di-devplatform-upload-action)
This change introduces the di-devplatform-upload-action into a build once deploy many matrix initially for the toy cri but for consideration in improving the existing matrix depoyments. 
- [OJ-1516](https://govukverify.atlassian.net/browse/OJ-1516)
- [OJ-1566](https://govukverify.atlassian.net/browse/OJ-1566)
[OJ-1516]: https://govukverify.atlassian.net/browse/OJ-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-1566]: https://govukverify.atlassian.net/browse/OJ-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> oj-1516 matrix deployment with dev platform action for toy cri

- .github/workflows/post-merge-matrix-deploy-toy.yml
- .secrets.baseline
Added dev matrix sign and publish job with toy dev configuration
- [OJ-1580](https://govukverify.atlassian.net/browse/OJ-1580)
[OJ-1580]: https://govukverify.atlassian.net/browse/OJ-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci:add dev matrix with toy config

- .github/workflows/pre-merge-checks-typescript.yml
Temporarily disable Sonarcloud scan due to misconfigured settings
> Disable Sonarcloud scan due to misconfiguration

- lambdas/src/handlers/audit-event-consumer-handler.ts
- lambdas/tests/unit/handlers/audit-event-consumer.test.ts
Updated the logging on audit event consumer
For clarity, it wasn't logging the event type which is one of the more important bits of information
- [OJ-1656](https://govukverify.atlassian.net/browse/OJ-1656)
[OJ-1656]: https://govukverify.atlassian.net/browse/OJ-1656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1656 update event logging to be clearer

- .secrets.baseline
- infrastructure/lambda/template.yaml
Added the mappings for KBV HMRC
- [OJ-1840](https://govukverify.atlassian.net/browse/OJ-1840)
[OJ-1840]: https://govukverify.atlassian.net/browse/OJ-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1840 add kbv hmrc mappings

- infrastructure/lambda/template.yaml
Update mappings to match renamed pipelines work
> Update common lambda mappings

- .github/workflows/pre-merge-integration-test.yml
- .secrets.baseline
Added workflow dispatch to the integration tests GHA so that we can run tests without having to raise a PR.
> Added workflow dispatch

- .gitignore
- .pre-commit-config.yaml
- .sdkmanrc
- .secrets.baseline
- deploy.sh
- infrastructure/lambda/template.yaml
- lambdas/.eslintignore
- lambdas/.eslintrc.js
- lambdas/.prettierignore
- lambdas/.prettierrc.js
- lambdas/.prettierrc.json
- lambdas/jest.config.ci.ts
- lambdas/jest.config.ts
- lambdas/sonar-project.properties
- lambdas/src/services/session-request-validator.ts
- lambdas/tests/unit/common/security/jwt-verifier.test.ts
- lambdas/tsconfig.eslint.json
- lambdas/tsconfig.json
- Update TypeScript config from the template repo
- Update the deployment script
Construct the stack name from the user's name and the CRI name if stack name has not been provided.
- Add the required gradle version to sdkman config
**Update pre-commit from the template repo**
- Update .secrets.baseline to exclude specific secrets and keywords
- Apply pre-commit changes
- Fix eslint warnings:
- unexpected any
- asserting on framework error messages which may change - use regex instead
> OJ-2209: Update typescript config from template repo

- .secrets.baseline
- infrastructure/lambda/template.yaml
Template updates for dynatrace
The changes got missed during initial updates
- [IPS-451-XXXX](https://govukverify.atlassian.net/browse/IPS-451)
- Required for dynatrace
> IPS-451 Add dynatrace updates to template

- .secrets.baseline
- infrastructure/lambda/template.yaml
IPS-451 Slight updates to layers
IPS-451 Slight updates to layers
- [IPS-451](https://govukverify.atlassian.net/browse/IPS-451)
[IPS-451]: https://govukverify.atlassian.net/browse/IPS-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-451 Slight updates to layers

- lambdas/tests/unit/common/config/config-service.test.ts
Apply linting changes from #263 
> chore: Apply linting to test files

- .github/workflows/pre-merge-checks-typescript.yml
- lambdas/package.json
Apply `package.json` changes from #263 
> Oj 2209/package json cleanup

- lambdas/src/common/services/audit-service.ts
- lambdas/src/types/audit-event.ts
- lambdas/tests/unit/common/services/audit-service.test.ts
Added `event_timestamp_ms`
TxMA requested this.
> BAU: Add event timestamp ms

- build.gradle
- session/src/main/java/uk/gov/di/ipv/cri/common/api/service/KMSRSADecrypter.java
- session/src/main/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestService.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/JWTDecrypterTest.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/KMSRSADecrypterTest.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SessionRequestServiceTest.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/service/SignedJWTBuilder.java
Updating Common_lib version to be latest. This is to pull in latest release which includes updates to the audit event timestamps so that they include milliseconds.
Updated build.gradle to make nimbus versioning inline with common-lib, some fixes where required as a part of this which can be seen in the KMSRSADecrypter.java
Additional Note:
will be reviewing other releases in between 1.4.3->1.5.6 to confirm no changes will be breaking in the jump in version
> LIME-1019 - Updating common_lib version

- build.gradle
- infrastructure/lambda/template.yaml
Created mock sqs queue for the dev environment 
To test the `Headers` value in the event messages for Address, KBV and Check CRIs 
- [OJ-2545](https://govukverify.atlassian.net/browse/OJ-2545)
- [OJ-2546](https://govukverify.atlassian.net/browse/OJ-2546)
- [OJ-2547](https://govukverify.atlassian.net/browse/OJ-2547)
[OJ-2545]: https://govukverify.atlassian.net/browse/OJ-2545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2546]: https://govukverify.atlassian.net/browse/OJ-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2547]: https://govukverify.atlassian.net/browse/OJ-2547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update template.yaml to include sqs event changes

- .github/workflows/deploy-branch.yml
- infrastructure/lambda/template.yaml
Sets CreateMockTxmaResourcesOverride to true for branch deploys so that audit queue is deployed for pre-merge tests
> OJ-2574 Sets CreateMockTxmaResourcesOverride to true for branch deploys

- deploy.sh
The deploy script has been updated to support cloudfront headers being passed to txma. 
- [LIME-1055](https://govukverify.atlassian.net/browse/LIME-1055)
[LIME-1055]: https://govukverify.atlassian.net/browse/LIME-1055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1055 changing deploy script for cloudfront

- README.md
- RELEASE_NOTES.md
Adds RELEASE_NOTES
So that teams are aware of changes that are being released when they re-deploy without having to trawl through commit history
> Adds RELEASE_NOTES

- infrastructure/lambda/template.yaml
Reverts govuk-one-login/ipv-cri-common-lambdas#307
Raised https://govukverify.atlassian.net/browse/OJ-2645
> Revert "BAU: Enable CSLS for check-hmrc-api"

- .github/workflows/post-merge-matrix-package.yml
- RELEASE_NOTES.md
Upgrade devplatform-upload-action
For DORA metrics
> Upgrade devplatform-upload-action

- lambdas/tests/unit/handlers/access-token-handler.test.ts
BAU: Fix failing unit test
The session `expiryDate` wasn't being explicitly set so was being polluted somehow
> BAU: Fix failing unit test

- build.gradle
Updated common lib reference to use latest version
> LIME-1271 - Updating lib version reference

- .github/workflows/package-test-resources.yml
- test-resources/README.md
- test-resources/infrastructure/samconfig.toml
- test-resources/infrastructure/template.yaml
- Updated workflow matrix
- Add KBV test harness domain
- Update README with step by step instructions
To deploy test resources to experian KBV account
- [OJ-2747](https://govukverify.atlassian.net/browse/OJ-2747)
[OJ-2747]: https://govukverify.atlassian.net/browse/OJ-2747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2747:  Add experian KBV to test resources

- build.gradle
Update to cri-lib version 3.1.3
AWS SDK version increased to 2.28.8
To bring in the latest changed in cri-lib.
Version increase as CRI lib changes where tested with 2.28.8.
- [LIME-1312](https://govukverify.atlassian.net/browse/LIME-1312)
[LIME-1312]: https://govukverify.atlassian.net/browse/LIME-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1312 Update to cri-lib version 3.1.3

- session/src/main/java/uk/gov/di/ipv/cri/common/api/domain/AuditEventExtensions.java
- session/src/main/java/uk/gov/di/ipv/cri/common/api/domain/Evidence.java
- session/src/main/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandler.java
- session/src/test/java/uk/gov/di/ipv/cri/common/api/handler/SessionHandlerTest.java
(PR-rebased)
Added context to sessionHandler.
So that IPV_DL_CRI_START Event contains Context Field (if present)
- [LIME-1287](https://govukverify.atlassian.net/browse/LIME-1287)
[LIME-1287]: https://govukverify.atlassian.net/browse/LIME-1287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1287 Added context to audit session item

- build.gradle
Update CRI to 3.2.1
To include a fix for postcode extraction in sharedclaims.
- [LIME-1312](https://govukverify.atlassian.net/browse/LIME-1312)
[LIME-1312]: https://govukverify.atlassian.net/browse/LIME-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1312 Update CRI to 3.2.1

- infrastructure/lambda/template.yaml
Common-Lambdas did not have a ProvisionedConcurrencyConfig section in the template for any lambdas this ProvisionedConcurrency was never enabled.
The configuration section is added based on two new maps 
- TSProvisionedConcurrencyMapping
- JavaProvisionedConcurrencyMapping
Not if JavaProvisionedConcurrencyMapping and JavaSnapStartMapping are set to values that try to enable both ProvisionedConcurrency and Snap-Start in the same environment - the deploy will fail.
There are situation where a non-code change are made, AutoPublishAliasAllProperties to help ensure new lambda versions are published in these cases.
To allow testing Java Lambdas with 
```
ProvisionedConcurrency Off Snap-Start Off
ProvisionedConcurrency ON  Snap-Start Off
ProvisionedConcurrency Off  Snap-Start ON
```
To also …
> LIME-1384 Add support for enabling ProvisionedConcurrency on Java or TS lambdas

- package-lock.json
Ran `npm audit fix`
https://github.com/govuk-one-login/ipv-cri-common-lambdas/security/dependabot/46
- [OJ-2920](https://govukverify.atlassian.net/browse/OJ-2920)
[OJ-2920]: https://govukverify.atlassian.net/browse/OJ-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2920: Address vulnerabilities

- package-lock.json
Fix vulnerabilities
- [OJ-3093](https://govukverify.atlassian.net/browse/OJ-3093)
[OJ-3093]: https://govukverify.atlassian.net/browse/OJ-3093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3093: Fix vulnerabilities

- .github/workflows/check-pr.yml
- .github/workflows/code-quality.yml
- .github/workflows/package-test-resources.yml
- .github/workflows/run-pact-tests-ts.yml
- .github/workflows/run-unit-tests-test-resources.yml
- .github/workflows/scan-repo.yml
- .github/workflows/test-resources-preview.yml
- package-lock.json
- test-resources/infrastructure/samconfig.toml
- test-resources/infrastructure/template.yaml
- test-resources/package.json
- Add deploy step to workflow
- Create CreateDomainResources condition because common lambdas doesn't have a custom domain set up
- Install data-vocab packages and update workflows to allow them to install
To deploy pre merge stacks for pre merge tests
- [OJ-3122](https://govukverify.atlassian.net/browse/OJ-3122)
[OJ-3122]: https://govukverify.atlassian.net/browse/OJ-3122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3122: Update test harness workflows

- .github/workflows/package-test-resources.yml
Add common CRI to package workflow
To deploy test resources to common accounts post merge
- [OJ-3130](https://govukverify.atlassian.net/browse/OJ-3130)
[OJ-3130]: https://govukverify.atlassian.net/browse/OJ-3130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3130: Add common CRI to package workflow

- infrastructure/lambda/template.yaml
Remove DL Provisioned Concurrency in integration+production
To pre-pare for enabling snap-start
- [LIME-1443](https://govukverify.atlassian.net/browse/LIME-1443)
[LIME-1443]: https://govukverify.atlassian.net/browse/LIME-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1443 - Remove DL Provisioned Concurrency in integration+production

- infrastructure/lambda/template.yaml
> feat: use the correct mapping in ENV_VAR_FEATURE_CONSUME_PUBLIC_JWK

- infrastructure/lambda/template.yaml
Enable key rotation in passport build
As part of roll out to higher envs
- [LIME-1645](https://govukverify.atlassian.net/browse/LIME-1645)
[LIME-1645]: https://govukverify.atlassian.net/browse/LIME-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1645 Set KeyRotationMapping to true for di-ipv-cri-passport-api (build)

- build.gradle
bump cri-lib to 5.0.2
There were changes to check for status codes in the JWKS endpoint
- [OJ-2972](https://govukverify.atlassian.net/browse/OJ-2972)
[OJ-2972]: https://govukverify.atlassian.net/browse/OJ-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bump: cri-lib to 5.0.2

- test-resources/infrastructure/template.yaml
Added integration to the TestHarnessUrl mapping
- [OJ-3171](https://govukverify.atlassian.net/browse/OJ-3171)
[OJ-3171]: https://govukverify.atlassian.net/browse/OJ-3171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add integration to TestHarnessUrl

- build.gradle
Bump cri-lib
Contains fix for GOAWAY frame
> chore: bump cri-lib version

- infrastructure/lambda/template.yaml
- Implement Deployment role for common lambda functions to enable canary deployment
- Implement deployment preference for each common lambda functions
- Implement Lambda alarms and 5XX erors for common lambda functions
- Add mapping to configure api gateway id for orange and lime services
- Deploy canary for common lambda functions
- Add deployment role, deployment preference, Lambda alarms, 5xx Error alarms for canary.
- Add mapping configuration to implement canary for Orange and lime services
- Enable canary in common lambda functions
- [IPS-1724](https://govukverify.atlassian.net/browse/IPS-1724)
[IPS-1724]: https://govukverify.atlassian.net/browse/IPS-1724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1724: Implement Canary deployment for common lambda functions

- infrastructure/lambda/template.yaml
Updated Stub JwksEndpoint url mapping for Lime CRIs 
Allow testing through the old core stub
- [LIME-1660](https://govukverify.atlassian.net/browse/LIME-1660)
[LIME-1660]: https://govukverify.atlassian.net/browse/LIME-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1660 Updated core stub mapping for lime

- infrastructure/lambda/template.yaml
- Implement Deployment role for common lambda functions to enable canary deployment
- Implement deployment preference for each common lambda functions
- Implement Lambda alarms and 5XX erors for common lambda functions
- Add mapping to configure api gateway id for orange and lime services
- Deploy canary for common lambda functions
- Update the mapping configuration for API Gateway in KBV account
- Enable canary in common lambda functions
- [IPS-1885](https://govukverify.atlassian.net/browse/IPS-1885)
[IPS-1885]: https://govukverify.atlassian.net/browse/IPS-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1885: Enable canary for common lambdas in KBV

- infrastructure/lambda/template.yaml
- Implement Deployment role for common lambda functions to enable canary deployment
- Implement deployment preference for each common lambda functions
- Implement Lambda alarms and 5XX erors for common lambda functions
- Add mapping to configure api gateway id for orange and lime services
- Deploy canary for common lambda functions in Address CRI
- Update the mapping configuration for API Gateway in Address account
- Enable canary in common lambda functions in Address CRI
- [IPS-1884](https://govukverify.atlassian.net/browse/IPS-1884)
[IPS-1884]: https://govukverify.atlassian.net/browse/IPS-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1884: Enable canary for common lambdas in Address CRI

- CODEOWNERS
Updated code owners so lime and orange can freely commit
Updated the codeowners file
So that Orange and Lime devs both have the ability to get review and merge PRs
> LIME-1723: Updated code owners to align lime and orange

- infrastructure/lambda/template.yaml
ENV_VAR_FEATURE_CONSUME_PUBLIC_JWK feature flag switched on in staging for testing.
- [LIME-1742](https://govukverify.atlassian.net/browse/LIME-1742)
[LIME-1742]: https://govukverify.atlassian.net/browse/LIME-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1742 Feature flag enabled to test in driving licence staging

- package-lock.json
Ran audit fix
https://github.com/govuk-one-login/ipv-cri-common-lambdas/security/dependabot/53
- [OJ-3271](https://govukverify.atlassian.net/browse/OJ-3271)
[OJ-3271]: https://govukverify.atlassian.net/browse/OJ-3271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3271: npm audit fix

- infrastructure/lambda/template.yaml
For passport staging:
- Switching key rotation alias flag to true
- Switching key rotation fallback flag to true
In preparation for key rotation implementation in staging on Monday.
- [LIME-1801](https://govukverify.atlassian.net/browse/LIME-1801)
[LIME-1801]: https://govukverify.atlassian.net/browse/LIME-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1801 | Switch key rotation alias to true and key rotation fallback to true for passport staging

- infrastructure/lambda/template.yaml
Fraud CRI - Enable KeyRotationLegacyFallback and KeyRotation in Integration
To enable key-rotations in Integration
- [LIME-1817](https://govukverify.atlassian.net/browse/LIME-1817)
[LIME-1817]: https://govukverify.atlassian.net/browse/LIME-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1817  Fraud CRI (Integration) - Enable Key Rotation

- infrastructure/lambda/template.yaml
DL CRI - Enable KeyRotationLegacyFallback and KeyRotation in staging
To enable key-rotations in staging
- [LIME-1819](https://govukverify.atlassian.net/browse/LIME-1819)
[LIME-1819]: https://govukverify.atlassian.net/browse/LIME-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1819 DL CRI (Staging) - Enable key rotation feature flags

- infrastructure/lambda/template.yaml
DL CRI - Enable KeyRotationLegacyFallback and KeyRotation in Integration
To enable key-rotations in Integration
- [LIME-1820](https://govukverify.atlassian.net/browse/LIME-1820)
[LIME-1820]: https://govukverify.atlassian.net/browse/LIME-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1820 DL CRI (Integration) - Enable key rotation feature flags
